export const destinationList = [
  {
    id: 1,
    name: '天池',
    location: '新疆阜康',
    description: '群山雪岭环抱的高山湖泊，是新疆最具代表性的自然名片之一。',
    image: 'https://images.unsplash.com/photo-1766823282156-7e2de7f9f922?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxUaWFuY2hpJTIwaGVhdmVubHklMjBsYWtlJTIwWGluamlhbmclMjBtb3VudGFpbnN8ZW58MXx8fHwxNzc2MjQ2MzMxfDA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: '4.8',
    category: '自然风光',
    coordinates: { longitude: 88.1548, latitude: 43.8803 },
    weather: {
      condition: '晴转多云',
      temperature: '18°C',
      humidity: '46%',
      wind: '3级山风',
    },
    tips: ['建议上午抵达，光线更通透', '山上温差较大，带一件防风外套', '缆车与徒步路线都适合拍照打卡'],
    suggestion: '适合安排半日到一日游，重点看湖景、雪山与林线层次。',
    liveTitle: '天池景区实时直播',
    liveHint: '可通过抖音查看景区实时天气、人流和湖面状态。',
    liveKeyword: '新疆天池 景区直播',
  },
  {
    id: 2,
    name: '喀什古城',
    location: '新疆喀什',
    description: '拱门、土墙与老街交织出丝路古城的烟火气与历史感。',
    image: 'https://images.unsplash.com/photo-1658423554035-ff01be23f31b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxLYXNoZ2FyJTIwb2xkJTIwY2l0eSUyMGFyY2hpdGVjdHVyZXxlbnwxfHx8fDE3NzYyNDYzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: '4.9',
    category: '人文古城',
    coordinates: { longitude: 75.9897, latitude: 39.4704 },
    weather: {
      condition: '晴',
      temperature: '24°C',
      humidity: '29%',
      wind: '2级微风',
    },
    tips: ['傍晚逛老城最有氛围', '建议穿舒适鞋子，巷道步行较多', '可结合夜市与民俗表演一起安排'],
    suggestion: '适合慢节奏漫游，体验老城建筑、茶馆、手工艺和夜市。',
    liveTitle: '喀什古城街景直播',
    liveHint: '抖音里常见街区实况直播，方便查看当前人流与夜景氛围。',
    liveKeyword: '喀什古城 直播',
  },
  {
    id: 3,
    name: '塔克拉玛干沙漠',
    location: '新疆塔里木盆地',
    description: '广袤流沙与公路穿越构成震撼景观，适合体验硬核西域之旅。',
    image: 'https://images.unsplash.com/photo-1623336343731-1582577b8250?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxUYWtsYW1ha2FuJTIwZGVzZXJ0JTIwc2FuZCUyMGR1bmVzfGVufDF8fHx8MTc3NjI0NjMzMnww&ixlib=rb-4.1.0&q=80&w=1080',
    rating: '4.7',
    category: '探险穿越',
    coordinates: { longitude: 83.6177, latitude: 39.0128 },
    weather: {
      condition: '晴热',
      temperature: '29°C',
      humidity: '18%',
      wind: '4级偏东风',
    },
    tips: ['必须准备补水与遮阳装备', '沙漠线路优先跟正规车队', '日落前后是最适合拍照的时段'],
    suggestion: '更适合有越野或沙漠体验需求的游客，建议报正规线路。',
    liveTitle: '沙漠公路直播',
    liveHint: '直播可帮助快速了解风沙情况、日照与路面状态。',
    liveKeyword: '塔克拉玛干沙漠 直播',
  },
  {
    id: 4,
    name: '喀纳斯',
    location: '新疆阿勒泰',
    description: '湖水清澈通透，秋季金林环绕，是北疆风光的代表目的地。',
    image: 'https://images.unsplash.com/photo-1698253542757-dcafef34a137?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxLYW5hcyUyMGxha2UlMjBhdXR1bW4lMjBsYW5kc2NhcGV8ZW58MXx8fHwxNzc2MjQ2MzMzfDA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: '4.9',
    category: '自然风光',
    coordinates: { longitude: 87.0347, latitude: 48.713 },
    weather: {
      condition: '多云',
      temperature: '13°C',
      humidity: '58%',
      wind: '2级山谷风',
    },
    tips: ['秋季旺季需尽早预订住宿', '早晨湖面容易出薄雾，适合拍照', '景区面积大，建议预留完整一天'],
    suggestion: '适合深度看风景与摄影爱好者，推荐秋天或初夏前往。',
    liveTitle: '喀纳斯湖景直播',
    liveHint: '可先看直播确认天气和云层，再决定当天拍摄路线。',
    liveKeyword: '喀纳斯 景区直播',
  },
  {
    id: 5,
    name: '伊犁草原毡房',
    location: '新疆伊犁河谷',
    description: '住进草原毡房，近距离感受牧歌生活与辽阔天幕。',
    image: 'https://images.unsplash.com/photo-1760776679643-0e28cbcd4214?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxncmFzc2xhbmQlMjB5dXJ0JTIwbm9tYWRpY3xlbnwxfHx8fDE3NzYyNDYzMzN8MA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: '4.6',
    category: '人文古城',
    coordinates: { longitude: 81.3179, latitude: 43.9228 },
    weather: {
      condition: '晴间多云',
      temperature: '21°C',
      humidity: '43%',
      wind: '2级草原风',
    },
    tips: ['夜晚温度下降快，建议准备外套', '可搭配骑马或草原下午茶', '注意防晒，紫外线较强'],
    suggestion: '适合亲子与轻度度假体验，节奏比较松弛。',
    liveTitle: '伊犁草原慢直播',
    liveHint: '适合先看草场天气、云层和现场氛围。',
    liveKeyword: '伊犁草原 直播',
  },
  {
    id: 6,
    name: '国际大巴扎',
    location: '新疆乌鲁木齐',
    description: '香料、织物和手工艺品汇聚，是体验城市烟火与夜色的热门地标。',
    image: 'https://images.unsplash.com/photo-1756363886854-b51467278a52?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYXphYXIlMjBtYXJrZXQlMjBzcGljZXMlMjBjb2xvcmZ1bHxlbnwxfHx8fDE3NzYyNDYzMzN8MA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: '4.5',
    category: '市集烟火',
    coordinates: { longitude: 87.6168, latitude: 43.7776 },
    weather: {
      condition: '晴',
      temperature: '26°C',
      humidity: '24%',
      wind: '2级微风',
    },
    tips: ['夜景灯光更出片', '可重点逛美食区和手工艺区', '注意高峰时段保管随身物品'],
    suggestion: '适合城市半日游，吃喝逛拍都比较集中。',
    liveTitle: '大巴扎实况直播',
    liveHint: '先看直播能快速判断夜市热度与摊位营业情况。',
    liveKeyword: '乌鲁木齐大巴扎 直播',
  },
]

export function getDestinationById(id) {
  return destinationList.find((item) => String(item.id) === String(id))
}

export function getDouyinSearchUrl(keyword) {
  return `https://www.douyin.com/search/${encodeURIComponent(keyword)}?type=live`
}
