function createScenicSpot({
  id,
  name,
  location,
  region,
  category,
  rating,
  longitude,
  latitude,
  description,
  image,
  weather,
  tips,
  suggestion,
  liveTitle,
  liveHint,
  liveKeyword,
}) {
  return {
    id,
    name,
    location,
    region: normalizeRegion(region),
    category,
    rating,
    coordinates: { longitude, latitude },
    description,
    image,
    weather,
    tips,
    suggestion,
    liveTitle,
    liveHint,
    liveKeyword,
  }
}

function normalizeRegion(region) {
  const regionMap = {
    '乌鲁木齐': '乌鲁木齐市',
    '乌鲁木齐周边': '乌鲁木齐市',
    '克拉玛依': '克拉玛依市',
    '吐鲁番': '吐鲁番市',
    '昌吉': '昌吉州',
    '博州': '博州',
    '巴州': '巴州',
    '阿克苏': '阿克苏地区',
    '喀什': '喀什地区',
    '和田': '和田地区',
    '伊犁': '伊犁州',
    '塔城': '塔城地区',
    '阿勒泰': '阿勒泰地区',
    '帕米尔高原': '喀什地区',
    '南疆环线': '巴州',
    '阿拉尔': '阿克苏地区',
  }

  return regionMap[region] || region
}

export const destinationList = [
  createScenicSpot({
    id: 1,
    name: '天山天池',
    location: '新疆阜康',
    region: '乌鲁木齐周边',
    category: '湖泊雪山',
    rating: '4.8',
    longitude: 88.1548,
    latitude: 43.8803,
    description: '高山湖泊与雪岭森林相映成景，是新疆最经典的入门景区之一。',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/%E5%A4%A9%E5%B1%B1%E5%A4%A9%E6%B1%A02_-_panoramio.jpg/1280px-%E5%A4%A9%E5%B1%B1%E5%A4%A9%E6%B1%A02_-_panoramio.jpg',
    weather: { condition: '晴转多云', temperature: '18°C', humidity: '46%', wind: '3级山风' },
    tips: ['建议上午抵达，湖面颜色更通透', '山上温差明显，带外套更稳妥', '适合缆车加环湖步道组合游玩'],
    suggestion: '适合半日到一日游，兼顾家庭游客与首次来新疆的观光需求。',
    liveTitle: '天山天池景区直播',
    liveHint: '先看直播可判断湖面能见度、天气和游客密度。',
    liveKeyword: '天山天池 景区直播',
  }),
  createScenicSpot({
    id: 2,
    name: '喀纳斯景区',
    location: '新疆阿勒泰布尔津',
    region: '阿勒泰',
    category: '湖泊雪山',
    rating: '4.9',
    longitude: 87.0347,
    latitude: 48.713,
    description: '以湖色、雪山、林海与图瓦风情闻名，是北疆核心景区。',
    image: 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Kanas_Lake%2C_China%2C_LandSat_image.jpg',
    weather: { condition: '多云', temperature: '13°C', humidity: '58%', wind: '2级山谷风' },
    tips: ['旺季住宿紧张，尽量提前预订', '清晨和傍晚最适合拍照', '建议预留完整一天以上'],
    suggestion: '适合深度摄影和自然风光爱好者，秋季层林尽染尤为出片。',
    liveTitle: '喀纳斯湖景直播',
    liveHint: '直播适合确认云层、湖色和当日景区人流。',
    liveKeyword: '喀纳斯 景区直播',
  }),
  createScenicSpot({
    id: 3,
    name: '赛里木湖',
    location: '新疆博州博乐',
    region: '博州',
    category: '湖泊雪山',
    rating: '4.9',
    longitude: 81.2014,
    latitude: 44.6002,
    description: '被称为大西洋最后一滴眼泪，湖岸、雪山与草甸构成纯净风景。',
    image: 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Satellite_Image_of_Lake_Sayram.png',
    weather: { condition: '晴', temperature: '16°C', humidity: '41%', wind: '4级湖风' },
    tips: ['环湖自驾体验最好', '湖边风大，注意保暖', '花期和日落都很值得停留'],
    suggestion: '适合自驾党和情侣游客，可与果子沟、霍城线路串联。',
    liveTitle: '赛里木湖风景直播',
    liveHint: '可通过直播先看湖色、天气和沿岸光线。',
    liveKeyword: '赛里木湖 直播',
  }),
  createScenicSpot({
    id: 4,
    name: '白沙湖景区',
    location: '新疆喀什塔县',
    region: '帕米尔高原',
    category: '湖泊雪山',
    rating: '4.8',
    longitude: 75.2436,
    latitude: 38.4412,
    description: '白沙山与蓝绿色湖水并置，画面干净而强烈，是帕米尔经典打卡点。',
    image: 'https://upload.wikimedia.org/wikipedia/commons/b/b9/Lake_Bulungkol_Karakoram_Highway_Kyrgyz_Xinjiang_China_%E6%96%B0%E7%96%86_%E5%90%89%E7%88%BE%E5%90%89%E6%96%AF_%E5%96%80%E5%96%87%E6%98%86%E4%BB%91%E5%85%AC%E8%B7%AF_%E7%99%BD%E6%B2%99%E6%B9%96_-_panoramio_%281%29.jpg',
    weather: { condition: '晴', temperature: '11°C', humidity: '32%', wind: '3级高原风' },
    tips: ['海拔较高，行动不要过急', '晴天湖色更惊艳', '与卡拉库里湖适合一天连游'],
    suggestion: '适合帕米尔公路旅行中的轻停留和高原风光拍摄。',
    liveTitle: '白沙湖实况直播',
    liveHint: '可用来观察高原天气与能见度变化。',
    liveKeyword: '白沙湖 直播',
  }),
  createScenicSpot({
    id: 5,
    name: '那拉提草原',
    location: '新疆伊犁新源',
    region: '伊犁',
    category: '草原森林',
    rating: '4.8',
    longitude: 83.0565,
    latitude: 43.4711,
    description: '空中草原层次起伏，适合看牧场、花海与雪岭线条。',
    image: 'https://upload.wikimedia.org/wikipedia/commons/d/d1/Nalati_Grassland_2.jpg',
    weather: { condition: '晴间多云', temperature: '20°C', humidity: '44%', wind: '2级草原风' },
    tips: ['骑马和观景车都很受欢迎', '午后紫外线强，注意防晒', '适合慢慢逛，不建议赶行程'],
    suggestion: '适合亲子、情侣和想感受伊犁草原氛围的游客。',
    liveTitle: '那拉提草原直播',
    liveHint: '直播有助于判断草原天气、云层和草场状态。',
    liveKeyword: '那拉提草原 直播',
  }),
  createScenicSpot({
    id: 6,
    name: '喀拉峻草原',
    location: '新疆伊犁特克斯',
    region: '伊犁',
    category: '草原森林',
    rating: '4.8',
    longitude: 82.6947,
    latitude: 43.2089,
    description: '人体草原、峡谷草甸与远山起伏交织，观景层次非常丰富。',
    image: 'https://bkimg.cdn.bcebos.com/pic/359b033b5bb5c9ea057e7162d539b6003bf3b3a5?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '多云', temperature: '19°C', humidity: '47%', wind: '3级山谷风' },
    tips: ['山路较多，尽量穿防滑鞋', '适合航拍和广角风景', '与特克斯八卦城可组合线路'],
    suggestion: '适合重景观路线，适合一天深度看草原和峡谷。',
    liveTitle: '喀拉峻草原直播',
    liveHint: '可通过直播先看草场颜色和天气。',
    liveKeyword: '喀拉峻草原 直播',
  }),
  createScenicSpot({
    id: 7,
    name: '巴音布鲁克景区',
    location: '新疆巴州和静',
    region: '巴州',
    category: '草原森林',
    rating: '4.7',
    longitude: 84.1472,
    latitude: 43.0339,
    description: '九曲十八弯与开阔草原相结合，是新疆看落日的招牌景区。',
    image: 'https://upload.wikimedia.org/wikipedia/commons/4/4f/Xinjiang_Bayinbuluke_China_%283715440219%29.jpg',
    weather: { condition: '晴', temperature: '17°C', humidity: '50%', wind: '3级草甸风' },
    tips: ['最佳时段在傍晚', '观景台风大，注意保暖', '旺季排队时间较长要预留余量'],
    suggestion: '适合落日摄影和草原线游玩，建议和独库沿线一起安排。',
    liveTitle: '巴音布鲁克直播',
    liveHint: '适合提前看当日云层和日落条件。',
    liveKeyword: '巴音布鲁克 直播',
  }),
  createScenicSpot({
    id: 8,
    name: '禾木景区',
    location: '新疆阿勒泰布尔津',
    region: '阿勒泰',
    category: '草原森林',
    rating: '4.9',
    longitude: 86.9962,
    latitude: 48.5485,
    description: '木屋村落、白桦林与晨雾构成了北疆最受欢迎的童话式风景。',
    image: 'https://upload.wikimedia.org/wikipedia/commons/3/3f/%E6%96%B0%E7%96%86-%E7%A6%BE%E6%9C%A8.%E9%BB%84%E6%98%8F_-_panoramio.jpg',
    weather: { condition: '多云', temperature: '10°C', humidity: '61%', wind: '2级林间风' },
    tips: ['清晨观景台值得早起', '秋季景色最好但人也最多', '夜晚温度低，注意保暖'],
    suggestion: '适合慢节奏住一晚，体验晨雾、木屋和白桦林。',
    liveTitle: '禾木村景直播',
    liveHint: '直播可以判断晨雾和当天游客量。',
    liveKeyword: '禾木村 直播',
  }),
  createScenicSpot({
    id: 9,
    name: '喀什古城',
    location: '新疆喀什',
    region: '喀什',
    category: '古城人文',
    rating: '4.9',
    longitude: 75.9897,
    latitude: 39.4704,
    description: '街巷、土墙与市井生活交织，是体验南疆烟火气的代表景区。',
    image: 'https://upload.wikimedia.org/wikipedia/commons/f/fc/East_gate_of_the_Ancient_City_of_Kashi_%2820230923104429%29.jpg',
    weather: { condition: '晴', temperature: '24°C', humidity: '29%', wind: '2级微风' },
    tips: ['傍晚逛老城最有氛围', '建议穿舒适鞋，步行较多', '适合和夜市、美食线路搭配'],
    suggestion: '适合城市漫游、人文拍摄和夜游体验。',
    liveTitle: '喀什古城街景直播',
    liveHint: '可用来观察当下人流和夜景氛围。',
    liveKeyword: '喀什古城 直播',
  }),
  createScenicSpot({
    id: 10,
    name: '交河故城',
    location: '新疆吐鲁番',
    region: '吐鲁番',
    category: '古城人文',
    rating: '4.6',
    longitude: 89.1446,
    latitude: 42.9512,
    description: '世界上保存较完整的生土建筑古城之一，遗址感非常强。',
    image: 'https://upload.wikimedia.org/wikipedia/commons/9/94/Jiaohe_City%28Yarkhoto%29%2CTurpan%2CXinjiang_HY2.jpg',
    weather: { condition: '晴热', temperature: '31°C', humidity: '16%', wind: '2级热风' },
    tips: ['白天非常晒，尽量避开正午', '适合配讲解更容易看懂', '和火焰山、坎儿井可连线'],
    suggestion: '适合对丝路历史和遗址建筑感兴趣的游客。',
    liveTitle: '交河故城直播',
    liveHint: '可先看现场日照和游客密度。',
    liveKeyword: '交河故城 直播',
  }),
  createScenicSpot({
    id: 11,
    name: '坎儿井民俗园',
    location: '新疆吐鲁番',
    region: '吐鲁番',
    category: '古城人文',
    rating: '4.5',
    longitude: 89.1906,
    latitude: 42.9511,
    description: '集中展示坎儿井灌溉智慧，是理解吐鲁番绿洲文明的重要一站。',
    image: 'https://bkimg.cdn.bcebos.com/pic/6f470395b5254f637af4806f?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '晴', temperature: '30°C', humidity: '19%', wind: '2级微风' },
    tips: ['可和葡萄沟同天安排', '适合带孩子了解工程智慧', '景区讲解内容值得听一段'],
    suggestion: '适合半日人文线路中的知识型体验。',
    liveTitle: '坎儿井景区直播',
    liveHint: '适合先看景区热度与当日开放情况。',
    liveKeyword: '坎儿井 直播',
  }),
  createScenicSpot({
    id: 12,
    name: '库车王府',
    location: '新疆阿克苏库车',
    region: '阿克苏',
    category: '古城人文',
    rating: '4.4',
    longitude: 82.9631,
    latitude: 41.7174,
    description: '兼具历史府邸与民族风情展示，适合了解库车老城文化。',
    image: 'https://bkimg.cdn.bcebos.com/pic/962bd40735fae6cd7b894727fee9182442a7d933a178?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '晴', temperature: '27°C', humidity: '25%', wind: '2级微风' },
    tips: ['适合配库车老城一起逛', '中午偏晒，尽量上午去', '可顺带体验南疆美食'],
    suggestion: '适合城市文化轻游和历史打卡。',
    liveTitle: '库车王府直播',
    liveHint: '可先看场内活动和游客情况。',
    liveKeyword: '库车王府 直播',
  }),
  createScenicSpot({
    id: 13,
    name: '库木塔格沙漠',
    location: '新疆鄯善',
    region: '吐鲁番',
    category: '沙漠峡谷',
    rating: '4.7',
    longitude: 90.2315,
    latitude: 42.8602,
    description: '城市与沙漠相连的独特景观，适合体验沙海与落日。',
    image: 'https://upload.wikimedia.org/wikipedia/commons/1/1d/%E4%B8%AD%E5%9B%BD%E6%96%B0%E7%96%86%E9%84%AF%E5%96%84%E5%8E%BF%E5%BA%93%E6%9C%A8%E5%A1%94%E6%A0%BC%E6%B2%99%E6%BC%A0_China_Xinjiang%2C_Piqan_County_Desert_Chi_-_panoramio.jpg',
    weather: { condition: '晴热', temperature: '32°C', humidity: '14%', wind: '3级偏东风' },
    tips: ['注意补水防晒', '傍晚比白天舒服很多', '可体验滑沙与骑骆驼项目'],
    suggestion: '适合轻沙漠体验和亲子玩乐，不必走得太深入。',
    liveTitle: '库木塔格沙漠直播',
    liveHint: '适合先看风沙和落日状态。',
    liveKeyword: '库木塔格沙漠 直播',
  }),
  createScenicSpot({
    id: 14,
    name: '天山神秘大峡谷',
    location: '新疆阿克苏库车',
    region: '阿克苏',
    category: '沙漠峡谷',
    rating: '4.8',
    longitude: 83.6959,
    latitude: 41.7725,
    description: '红色峡谷线条凌厉，光影变化强烈，是南疆最有震撼感的峡谷之一。',
    image: 'https://bkimg.cdn.bcebos.com/pic/267f9e2f070828385ce621b2b699a9014d08f1a9',
    weather: { condition: '晴', temperature: '28°C', humidity: '23%', wind: '2级山口风' },
    tips: ['尽量穿防滑鞋', '下雨天留意临时关闭信息', '适合广角和竖构图拍摄'],
    suggestion: '适合喜欢地貌和大片感风景的游客。',
    liveTitle: '神秘大峡谷直播',
    liveHint: '可提前观察天气和光照条件。',
    liveKeyword: '天山神秘大峡谷 直播',
  }),
  createScenicSpot({
    id: 15,
    name: '乌尔禾魔鬼城',
    location: '新疆克拉玛依',
    region: '克拉玛依',
    category: '沙漠峡谷',
    rating: '4.6',
    longitude: 85.7634,
    latitude: 46.0879,
    description: '雅丹地貌广阔奇诡，日落时分色调尤为震撼。',
    image: 'https://bkimg.cdn.bcebos.com/pic/5fdf8db1cb1349540923a1895d198558d109b2dedc9d?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '晴', temperature: '25°C', humidity: '20%', wind: '4级风' },
    tips: ['傍晚观光车体验最佳', '风沙较大注意护目', '适合电影感照片'],
    suggestion: '适合与北疆环线搭配，突出地貌体验。',
    liveTitle: '魔鬼城实况直播',
    liveHint: '直播有助于判断天空和光线层次。',
    liveKeyword: '魔鬼城 直播',
  }),
  createScenicSpot({
    id: 16,
    name: '塔克拉玛干沙漠',
    location: '新疆塔里木盆地',
    region: '南疆环线',
    category: '沙漠峡谷',
    rating: '4.7',
    longitude: 83.6177,
    latitude: 39.0128,
    description: '广袤沙海与穿沙公路组成极具西域张力的探险风景。',
    image: 'https://images.unsplash.com/photo-1623336343731-1582577b8250?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxUYWtsYW1ha2FuJTIwZGVzZXJ0JTIwc2FuZCUyMGR1bmVzfGVufDF8fHx8MTc3NjI0NjMzMnww&ixlib=rb-4.1.0&q=80&w=1080',
    weather: { condition: '晴热', temperature: '29°C', humidity: '18%', wind: '4级偏东风' },
    tips: ['补水与遮阳必须到位', '尽量跟正规线路或车队', '日出日落最有氛围'],
    suggestion: '适合越野、自驾和重度风景体验者。',
    liveTitle: '塔克拉玛干直播',
    liveHint: '可先看风沙和道路天气情况。',
    liveKeyword: '塔克拉玛干沙漠 直播',
  }),
  createScenicSpot({
    id: 17,
    name: '泽普金湖杨景区',
    location: '新疆喀什泽普',
    region: '喀什',
    category: '胡杨湿地',
    rating: '4.7',
    longitude: 77.2708,
    latitude: 38.1846,
    description: '胡杨、湿地和湖岸并存，秋季色彩层次很丰富。',
    image: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    weather: { condition: '晴', temperature: '22°C', humidity: '34%', wind: '2级微风' },
    tips: ['秋天是最佳季节', '适合轻松散步和慢拍', '建议安排半天即可'],
    suggestion: '适合秋季南疆线路中的轻休闲景区。',
    liveTitle: '金湖杨秋景直播',
    liveHint: '可先看胡杨色彩和天气状态。',
    liveKeyword: '泽普金湖杨 直播',
  }),
  createScenicSpot({
    id: 18,
    name: '轮台胡杨林公园',
    location: '新疆巴州轮台',
    region: '巴州',
    category: '胡杨湿地',
    rating: '4.8',
    longitude: 84.2556,
    latitude: 41.7812,
    description: '塔里木胡杨林规模大，秋色与河道湿地组合很有辨识度。',
    image: 'https://bkimg.cdn.bcebos.com/pic/3b6833f59a17901bbd31090c?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '晴', temperature: '20°C', humidity: '31%', wind: '2级河谷风' },
    tips: ['秋季黄金期游客较多', '景区较大，适合观光车', '逆光和黄昏很适合拍照'],
    suggestion: '适合秋季专项摄影和胡杨主题旅行。',
    liveTitle: '轮台胡杨林直播',
    liveHint: '适合确认叶色、光线和当日客流。',
    liveKeyword: '轮台胡杨林 直播',
  }),
  createScenicSpot({
    id: 19,
    name: '博斯腾湖',
    location: '新疆巴州博湖',
    region: '巴州',
    category: '胡杨湿地',
    rating: '4.6',
    longitude: 86.8207,
    latitude: 41.8576,
    description: '湖区开阔，芦苇湿地和水上项目都比较成熟，是巴州休闲景区代表。',
    image: 'https://bkimg.cdn.bcebos.com/pic/359b033b5bb5c9eafd2e54f9d839b6003bf3b3cf?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '晴', temperature: '21°C', humidity: '45%', wind: '3级湖风' },
    tips: ['适合夏秋季前往', '可选择乘船项目', '注意湖边风力变化'],
    suggestion: '适合家庭休闲和亲水轻度游玩。',
    liveTitle: '博斯腾湖直播',
    liveHint: '可先看湖面风况和天气。',
    liveKeyword: '博斯腾湖 直播',
  }),
  createScenicSpot({
    id: 20,
    name: '可可托海景区',
    location: '新疆阿勒泰富蕴',
    region: '阿勒泰',
    category: '峡谷地貌',
    rating: '4.8',
    longitude: 89.8374,
    latitude: 46.9876,
    description: '峡谷、河谷、矿坑与白桦林组合独特，四季景观差异明显。',
    image: 'https://upload.wikimedia.org/wikipedia/commons/2/26/%E6%96%B0%E7%96%86-%E5%8F%AF%E5%8F%AF%E6%89%98%E6%B5%B7-%E7%BE%8E%E4%B8%BD%E7%9A%84%E9%A3%8E%E6%99%AF_-_panoramio.jpg',
    weather: { condition: '多云', temperature: '12°C', humidity: '56%', wind: '2级山风' },
    tips: ['景区纵深较大，穿舒适鞋', '秋色和溪流特别适合拍摄', '建议预留大半天'],
    suggestion: '适合自然控和摄影用户，值得慢逛。',
    liveTitle: '可可托海直播',
    liveHint: '直播可帮助判断山谷天气和客流。',
    liveKeyword: '可可托海 直播',
  }),
  createScenicSpot({
    id: 21,
    name: '江布拉克景区',
    location: '新疆昌吉奇台',
    region: '昌吉',
    category: '峡谷地貌',
    rating: '4.7',
    longitude: 89.6812,
    latitude: 43.9248,
    description: '麦田、山谷和林带线条优美，是天山北麓的高颜值景区。',
    image: 'https://bkimg.cdn.bcebos.com/pic/d31b0ef41bd5ad6eddc4a50848932edbb6fd53669682?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '晴', temperature: '19°C', humidity: '42%', wind: '2级山地风' },
    tips: ['夏季麦浪和秋色都值得看', '自驾体验更自由', '可拍公路与田野层次'],
    suggestion: '适合周末自驾和轻摄影路线。',
    liveTitle: '江布拉克实况直播',
    liveHint: '适合提前看天气和田野状态。',
    liveKeyword: '江布拉克 直播',
  }),
  createScenicSpot({
    id: 22,
    name: '帕米尔旅游区',
    location: '新疆喀什塔县',
    region: '帕米尔高原',
    category: '峡谷地貌',
    rating: '4.9',
    longitude: 75.2261,
    latitude: 37.7789,
    description: '雪峰、公路、高原湖泊与边境风光并存，是新疆极具辨识度的大景区。',
    image: 'https://bkimg.cdn.bcebos.com/pic/77c6a7efce1b9d16fdfadc18f185a38f8c5494eece0d?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '晴', temperature: '9°C', humidity: '28%', wind: '3级高原风' },
    tips: ['注意高海拔适应', '证件带齐', '建议预留整天甚至两天'],
    suggestion: '适合公路旅行和高原风景重度爱好者。',
    liveTitle: '帕米尔旅游区直播',
    liveHint: '适合看能见度、天气与路况氛围。',
    liveKeyword: '帕米尔 直播',
  }),
  createScenicSpot({
    id: 23,
    name: '国际大巴扎',
    location: '新疆乌鲁木齐',
    region: '乌鲁木齐',
    category: '城市夜游',
    rating: '4.5',
    longitude: 87.6168,
    latitude: 43.7776,
    description: '香料、织物和手工艺品汇聚，是体验城市烟火气的热门地标。',
    image: 'https://upload.wikimedia.org/wikipedia/commons/2/29/%E6%96%B0%E7%96%86%E4%B9%8C%E9%B2%81%E6%9C%A8%E9%BD%90%E5%9B%BD%E9%99%85%E5%A4%A7%E5%B7%B4%E6%89%8E.jpg',
    weather: { condition: '晴', temperature: '26°C', humidity: '24%', wind: '2级微风' },
    tips: ['夜景灯光更出片', '可重点逛美食区和手工艺区', '高峰时段注意保管物品'],
    suggestion: '适合城市半日游，吃喝逛拍都比较集中。',
    liveTitle: '大巴扎实况直播',
    liveHint: '先看直播能快速判断夜市热度与营业状态。',
    liveKeyword: '乌鲁木齐大巴扎 直播',
  }),
  createScenicSpot({
    id: 24,
    name: '葡萄沟景区',
    location: '新疆吐鲁番',
    region: '吐鲁番',
    category: '城市夜游',
    rating: '4.5',
    longitude: 89.1601,
    latitude: 42.9964,
    description: '葡萄长廊、绿洲庭院与民俗表演结合，是吐鲁番经典休闲景区。',
    image: 'https://upload.wikimedia.org/wikipedia/commons/4/42/Turpan_grape_valley.jpg',
    weather: { condition: '晴热', temperature: '30°C', humidity: '18%', wind: '2级微风' },
    tips: ['适合下午和傍晚游玩', '可顺带体验葡萄采摘季', '适合带长辈和小孩'],
    suggestion: '适合轻松休闲路线，与火焰山、坎儿井串联很顺。',
    liveTitle: '葡萄沟景区直播',
    liveHint: '可先看园区绿荫状态和游客热度。',
    liveKeyword: '葡萄沟 直播',
  }),
  createScenicSpot({
    id: 25,
    name: '卡拉库里湖',
    location: '新疆喀什塔县',
    region: '帕米尔高原',
    category: '湖泊雪山',
    rating: '4.8',
    longitude: 75.0955,
    latitude: 38.4471,
    description: '湖面倒映慕士塔格峰，适合高原公路旅行中的经典停留。',
    image: 'https://bkimg.cdn.bcebos.com/pic/838ba61ea8d3fd1f4134984abb19321f95cad1c8f13e?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '晴', temperature: '8°C', humidity: '30%', wind: '3级高原风' },
    tips: ['高海拔地区注意节奏', '晴天倒影效果更好', '可与白沙湖顺路联游'],
    suggestion: '适合帕米尔线观景打卡和高原风景拍摄。',
    liveTitle: '卡拉库里湖直播',
    liveHint: '适合提前看天气、云层和雪山能见度。',
    liveKeyword: '卡拉库里湖 直播',
  }),
  createScenicSpot({
    id: 26,
    name: '慕士塔格冰川公园',
    location: '新疆喀什塔县',
    region: '帕米尔高原',
    category: '湖泊雪山',
    rating: '4.7',
    longitude: 75.1172,
    latitude: 38.2835,
    description: '雪峰、冰川与高原地貌并置，是帕米尔线上视觉冲击很强的景区。',
    image: 'https://bkimg.cdn.bcebos.com/pic/b812c8fcc3cec3fda160fc3dd688d43f8794271f?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '多云', temperature: '4°C', humidity: '36%', wind: '4级山风' },
    tips: ['注意保暖和防晒', '适合晴朗天气前往', '海拔较高量力而行'],
    suggestion: '适合想近距离看冰川和雪峰的高原旅行者。',
    liveTitle: '慕士塔格冰川直播',
    liveHint: '可先看云层厚度和现场雪线状态。',
    liveKeyword: '慕士塔格冰川 直播',
  }),
  createScenicSpot({
    id: 27,
    name: '昭苏湿地公园',
    location: '新疆伊犁昭苏',
    region: '伊犁',
    category: '草原森林',
    rating: '4.6',
    longitude: 81.1381,
    latitude: 43.1578,
    description: '湿地花海与草原开阔感并存，适合夏季看天马与花田。',
    image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    weather: { condition: '晴', temperature: '18°C', humidity: '48%', wind: '2级草甸风' },
    tips: ['夏季花期更适合前往', '清晨光线更柔和', '可和天马浴河线路搭配'],
    suggestion: '适合轻松拍照和伊犁夏季花海体验。',
    liveTitle: '昭苏湿地直播',
    liveHint: '可先看花海状态和当天天气。',
    liveKeyword: '昭苏湿地 直播',
  }),
  createScenicSpot({
    id: 28,
    name: '夏塔景区',
    location: '新疆伊犁昭苏',
    region: '伊犁',
    category: '草原森林',
    rating: '4.8',
    longitude: 80.6549,
    latitude: 42.8957,
    description: '雪山、草原与古道并存，是伊犁兼具徒步感和大景观的代表景区。',
    image: 'https://bkimg.cdn.bcebos.com/pic/37d12f2eb9389b50e85e06a78f35e5dde6116ea6?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '多云', temperature: '14°C', humidity: '53%', wind: '3级山口风' },
    tips: ['步道较长建议量力而行', '带防风外套', '适合晴天或多云天气前往'],
    suggestion: '适合喜欢雪山草原和轻徒步的游客。',
    liveTitle: '夏塔古道直播',
    liveHint: '直播可以先看天气和雪山显露情况。',
    liveKeyword: '夏塔景区 直播',
  }),
  createScenicSpot({
    id: 29,
    name: '特克斯八卦城',
    location: '新疆伊犁特克斯',
    region: '伊犁',
    category: '古城人文',
    rating: '4.5',
    longitude: 82.5006,
    latitude: 43.2176,
    description: '城市布局独特，适合感受伊犁县城生活和俯瞰式城市格局。',
    image: 'https://bkimg.cdn.bcebos.com/pic/f703738da9773912b31bc4b983559118367adbb4449c?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '晴', temperature: '23°C', humidity: '37%', wind: '2级微风' },
    tips: ['适合傍晚逛夜市', '可搭配离街美食', '航拍视角更能体现特色'],
    suggestion: '适合城市轻游和伊犁县城文化体验。',
    liveTitle: '特克斯八卦城直播',
    liveHint: '可先看街区热度和夜间氛围。',
    liveKeyword: '特克斯八卦城 直播',
  }),
  createScenicSpot({
    id: 30,
    name: '高昌故城',
    location: '新疆吐鲁番',
    region: '吐鲁番',
    category: '古城人文',
    rating: '4.6',
    longitude: 89.5261,
    latitude: 42.8589,
    description: '丝路古城遗址规模大，和交河故城一起构成吐鲁番人文主线。',
    image: 'https://bkimg.cdn.bcebos.com/pic/b3119313b07eca8065384dee9c7b80dda144ad342538?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '晴热', temperature: '32°C', humidity: '15%', wind: '2级热风' },
    tips: ['建议早晚游览', '遗址面积大注意补水', '配讲解更容易看懂'],
    suggestion: '适合对西域历史和古城遗址感兴趣的游客。',
    liveTitle: '高昌故城直播',
    liveHint: '适合看日照强度和当日游客量。',
    liveKeyword: '高昌故城 直播',
  }),
  createScenicSpot({
    id: 31,
    name: '火焰山景区',
    location: '新疆吐鲁番',
    region: '吐鲁番',
    category: '沙漠峡谷',
    rating: '4.4',
    longitude: 89.4922,
    latitude: 42.9127,
    description: '红色山体与炽热感十足的地貌画面，是吐鲁番最具辨识度的地标之一。',
    image: 'https://upload.wikimedia.org/wikipedia/commons/7/71/%E7%81%AB%E7%84%B0%E5%B1%B1%E4%B8%AD%E6%99%AF.jpg',
    weather: { condition: '晴热', temperature: '36°C', humidity: '10%', wind: '2级热风' },
    tips: ['尽量避开午后高温', '带足饮用水', '适合短时打卡不宜久留'],
    suggestion: '适合吐鲁番经典线路中的短停留型景区。',
    liveTitle: '火焰山实况直播',
    liveHint: '可先看现场热度和游客密度。',
    liveKeyword: '火焰山 直播',
  }),
  createScenicSpot({
    id: 32,
    name: '温宿大峡谷',
    location: '新疆阿克苏温宿',
    region: '阿克苏',
    category: '沙漠峡谷',
    rating: '4.7',
    longitude: 79.2216,
    latitude: 41.4889,
    description: '红层峡谷色彩浓烈，线条变化丰富，极具西部荒野感。',
    image: 'https://bkimg.cdn.bcebos.com/pic/d01373f082025aaf18956ec1f4edab64034f1a10?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '晴', temperature: '27°C', humidity: '21%', wind: '3级峡谷风' },
    tips: ['穿防滑鞋更方便', '晴天更能体现色彩层次', '适合广角拍摄'],
    suggestion: '适合地貌控和阿克苏自驾线路用户。',
    liveTitle: '温宿大峡谷直播',
    liveHint: '适合提前看天气、光影和开放状态。',
    liveKeyword: '温宿大峡谷 直播',
  }),
  createScenicSpot({
    id: 33,
    name: '罗布人村寨',
    location: '新疆巴州尉犁',
    region: '巴州',
    category: '胡杨湿地',
    rating: '4.5',
    longitude: 86.2676,
    latitude: 40.5972,
    description: '胡杨、塔里木河与沙漠民俗融合，兼具风景与文化体验。',
    image: 'https://bkimg.cdn.bcebos.com/pic/d439b6003af33a87e95094d7650607385343faf21ff1?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '晴', temperature: '24°C', humidity: '29%', wind: '2级河谷风' },
    tips: ['秋季胡杨更有看点', '适合拍水岸和胡杨倒影', '可体验民俗展示项目'],
    suggestion: '适合巴州线轻文化和秋景体验。',
    liveTitle: '罗布人村寨直播',
    liveHint: '适合提前看胡杨状态和当日天气。',
    liveKeyword: '罗布人村寨 直播',
  }),
  createScenicSpot({
    id: 34,
    name: '天鹅河景区',
    location: '新疆巴州库尔勒',
    region: '巴州',
    category: '胡杨湿地',
    rating: '4.4',
    longitude: 86.1709,
    latitude: 41.7259,
    description: '城市湿地与水系景观融为一体，适合夜景和休闲散步。',
    image: 'https://bkimg.cdn.bcebos.com/pic/caef76094b36acaf51264a5b72d98d1000e99c57?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '晴', temperature: '22°C', humidity: '40%', wind: '2级河风' },
    tips: ['傍晚最适合散步', '适合带孩子轻松走走', '夜景灯光更有氛围'],
    suggestion: '适合城市休闲和库尔勒夜游。',
    liveTitle: '天鹅河景区直播',
    liveHint: '可先看夜景灯光和现场热度。',
    liveKeyword: '天鹅河 直播',
  }),
  createScenicSpot({
    id: 35,
    name: '独库公路北段观景线',
    location: '新疆独山子',
    region: '克拉玛依',
    category: '峡谷地貌',
    rating: '4.9',
    longitude: 84.9187,
    latitude: 44.3281,
    description: '雪山、草原、峡谷和公路天际线不断切换，是新疆自驾必打卡路线。',
    image: 'https://bkimg.cdn.bcebos.com/pic/78310a55b319ebc4b7452225007dd8fc1e178a82b84e?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '多云', temperature: '15°C', humidity: '46%', wind: '3级山口风' },
    tips: ['关注通车时间', '天气变化快需备外套', '适合多停靠几处观景点'],
    suggestion: '适合自驾党和喜欢一路看多种地貌的人群。',
    liveTitle: '独库公路北段直播',
    liveHint: '可用于看天气、车流和山口云层。',
    liveKeyword: '独库公路 直播',
  }),
  createScenicSpot({
    id: 36,
    name: '安集海大峡谷',
    location: '新疆塔城沙湾',
    region: '塔城',
    category: '峡谷地貌',
    rating: '4.7',
    longitude: 85.4408,
    latitude: 44.1651,
    description: '彩色冲刷地貌层理分明，是近年很热门的航拍型景区。',
    image: 'https://images.unsplash.com/photo-1464823063530-08f10ed1a2dd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    weather: { condition: '晴', temperature: '21°C', humidity: '33%', wind: '3级峡谷风' },
    tips: ['注意安全边界不要靠边', '晴天色彩更浓烈', '适合广角和无人机拍摄'],
    suggestion: '适合短途自驾和重画面感拍摄。',
    liveTitle: '安集海大峡谷直播',
    liveHint: '可提前看天气和地貌观感。',
    liveKeyword: '安集海大峡谷 直播',
  }),
  createScenicSpot({
    id: 37,
    name: '乌孙古道入口景区',
    location: '新疆伊犁特克斯',
    region: '伊犁',
    category: '峡谷地貌',
    rating: '4.6',
    longitude: 82.0277,
    latitude: 42.9294,
    description: '峡谷、河谷与古道徒步氛围并存，适合户外向游客。',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    weather: { condition: '多云', temperature: '13°C', humidity: '54%', wind: '3级山谷风' },
    tips: ['建议跟有经验线路', '提前看天气', '穿徒步鞋更稳妥'],
    suggestion: '适合轻户外或想感受古道氛围的游客。',
    liveTitle: '乌孙古道直播',
    liveHint: '可先看云层和谷地天气。',
    liveKeyword: '乌孙古道 直播',
  }),
  createScenicSpot({
    id: 38,
    name: '新疆博物馆',
    location: '新疆乌鲁木齐',
    region: '乌鲁木齐',
    category: '古城人文',
    rating: '4.8',
    longitude: 87.5923,
    latitude: 43.8262,
    description: '系统展示新疆历史、民族与丝路文明，是入疆后很适合第一站了解背景的地方。',
    image: 'https://bkimg.cdn.bcebos.com/pic/86d6277f9e2f070891da472fee24b899a801f2c6?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '晴', temperature: '25°C', humidity: '27%', wind: '2级微风' },
    tips: ['建议预约并错峰参观', '先看常设展更有效率', '适合亲子和知识型游客'],
    suggestion: '适合作为新疆旅行的背景铺垫站。',
    liveTitle: '新疆博物馆周边直播',
    liveHint: '可先看当日排队和客流情况。',
    liveKeyword: '新疆博物馆 直播',
  }),
  createScenicSpot({
    id: 39,
    name: '红山公园',
    location: '新疆乌鲁木齐',
    region: '乌鲁木齐',
    category: '城市夜游',
    rating: '4.4',
    longitude: 87.6162,
    latitude: 43.8031,
    description: '城市高点视野开阔，适合看乌鲁木齐日落和夜景轮廓。',
    image: 'https://bkimg.cdn.bcebos.com/pic/08f790529822720ef082e22775cb0a46f31fab9b?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '晴', temperature: '24°C', humidity: '28%', wind: '2级晚风' },
    tips: ['傍晚更适合登高', '适合城市俯瞰照片', '安排1到2小时即可'],
    suggestion: '适合城市轻松游和夜景打卡。',
    liveTitle: '红山公园夜景直播',
    liveHint: '适合观察夕阳和城市灯光状态。',
    liveKeyword: '红山公园 直播',
  }),
  createScenicSpot({
    id: 40,
    name: '达坂城古镇',
    location: '新疆乌鲁木齐达坂城',
    region: '乌鲁木齐周边',
    category: '城市夜游',
    rating: '4.3',
    longitude: 88.3128,
    latitude: 43.3584,
    description: '风车、古镇街巷与边塞氛围并置，适合乌鲁木齐周边短途。',
    image: 'https://images.unsplash.com/photo-1494526585095-c41746248156?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    weather: { condition: '晴', temperature: '23°C', humidity: '22%', wind: '4级风' },
    tips: ['风力较强注意保暖', '适合周边半日游', '可顺带体验风车景观'],
    suggestion: '适合城市周边轻出行和边塞风情打卡。',
    liveTitle: '达坂城古镇直播',
    liveHint: '适合先看风力和古镇热度。',
    liveKeyword: '达坂城古镇 直播',
  }),
  createScenicSpot({
    id: 41,
    name: '果子沟大桥观景台',
    location: '新疆伊犁霍城',
    region: '伊犁',
    category: '峡谷地貌',
    rating: '4.8',
    longitude: 81.0562,
    latitude: 44.2298,
    description: '山谷、公路桥和森林牧坡同框，是伊犁入门级大片机位。',
    image: 'https://bkimg.cdn.bcebos.com/pic/6d81800a19d8bc3eee230c9c8d8ba61ea8d345b8?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '晴', temperature: '17°C', humidity: '43%', wind: '3级山谷风' },
    tips: ['上午逆光少更好拍', '观景点停车要注意安全', '适合搭配赛里木湖同日路线'],
    suggestion: '适合伊犁自驾途中短暂停留和拍全景。',
    liveTitle: '果子沟观景直播',
    liveHint: '适合先看云层和桥面能见度。',
    liveKeyword: '果子沟大桥 直播',
  }),
  createScenicSpot({
    id: 42,
    name: '霍城薰衣草庄园',
    location: '新疆伊犁霍城',
    region: '伊犁',
    category: '草原森林',
    rating: '4.5',
    longitude: 80.9331,
    latitude: 44.1096,
    description: '花田色块和远山同框，是伊犁夏季热门赏花景区。',
    image: 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    weather: { condition: '晴', temperature: '22°C', humidity: '39%', wind: '2级微风' },
    tips: ['花期集中在夏季', '建议穿浅色衣服更出片', '傍晚光线更柔和'],
    suggestion: '适合夏季打卡和轻松拍照。',
    liveTitle: '霍城薰衣草直播',
    liveHint: '可先看花田开放状态和天气。',
    liveKeyword: '霍城薰衣草 直播',
  }),
  createScenicSpot({
    id: 43,
    name: '琼库什台',
    location: '新疆伊犁特克斯',
    region: '伊犁',
    category: '草原森林',
    rating: '4.8',
    longitude: 82.9923,
    latitude: 42.9948,
    description: '原生态村落和起伏草坡保留着很强的边地自然气质。',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    weather: { condition: '多云', temperature: '13°C', humidity: '55%', wind: '2级山风' },
    tips: ['路况变化快，尽量白天进出', '住一晚更能感受氛围', '适合徒步和骑马'],
    suggestion: '适合慢旅行和想看原生态草原村落的游客。',
    liveTitle: '琼库什台直播',
    liveHint: '适合看天气和山间云雾状态。',
    liveKeyword: '琼库什台 直播',
  }),
  createScenicSpot({
    id: 44,
    name: '唐布拉草原',
    location: '新疆伊犁尼勒克',
    region: '伊犁',
    category: '草原森林',
    rating: '4.7',
    longitude: 83.3072,
    latitude: 43.5634,
    description: '百里画廊串联草场、雪山和溪谷，是伊犁另一条高颜值景观线。',
    image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    weather: { condition: '晴', temperature: '18°C', humidity: '45%', wind: '3级谷风' },
    tips: ['适合自驾慢慢停靠', '夏季景色最稳定', '注意午后阵雨变化'],
    suggestion: '适合景观自驾和家庭用户。',
    liveTitle: '唐布拉直播',
    liveHint: '可先看草场天气和道路状态。',
    liveKeyword: '唐布拉草原 直播',
  }),
  createScenicSpot({
    id: 45,
    name: '乌伦古湖',
    location: '新疆阿勒泰福海',
    region: '阿勒泰',
    category: '湖泊雪山',
    rating: '4.5',
    longitude: 87.4942,
    latitude: 47.2211,
    description: '湖面宽阔，适合看日落、候鸟和安静湖岸风景。',
    image: 'https://bkimg.cdn.bcebos.com/pic/d1160924ab18972bd407bc8fd8966c899e510fb39c79?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '晴', temperature: '15°C', humidity: '49%', wind: '3级湖风' },
    tips: ['傍晚适合看落日', '风大时注意保暖', '适合安静休闲型游客'],
    suggestion: '适合阿勒泰线中安静看湖的半日游。',
    liveTitle: '乌伦古湖直播',
    liveHint: '适合先看风况和落日云层。',
    liveKeyword: '乌伦古湖 直播',
  }),
  createScenicSpot({
    id: 46,
    name: '五彩滩',
    location: '新疆阿勒泰布尔津',
    region: '阿勒泰',
    category: '峡谷地貌',
    rating: '4.8',
    longitude: 86.7557,
    latitude: 48.1248,
    description: '额尔齐斯河岸边的彩色丘陵，在夕阳下层次感非常强。',
    image: 'https://bkimg.cdn.bcebos.com/pic/622762d0f703918fa0ece42e7876319759ee3c6d6e89?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '晴', temperature: '14°C', humidity: '42%', wind: '3级河谷风' },
    tips: ['最佳时段在傍晚', '风大时注意帽子和外套', '适合拍河岸层理变化'],
    suggestion: '适合短时打卡和黄昏摄影。',
    liveTitle: '五彩滩直播',
    liveHint: '可先看夕阳和云层条件。',
    liveKeyword: '五彩滩 直播',
  }),
  createScenicSpot({
    id: 47,
    name: '白哈巴村',
    location: '新疆阿勒泰哈巴河',
    region: '阿勒泰',
    category: '草原森林',
    rating: '4.8',
    longitude: 86.6174,
    latitude: 48.9067,
    description: '边境木屋村与林海山谷交织，氛围安静而原始。',
    image: 'https://bkimg.cdn.bcebos.com/pic/dc54564e9258d109b3ded90a9601dbbf6c81800ae748?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '多云', temperature: '9°C', humidity: '59%', wind: '2级林风' },
    tips: ['适合住一晚看晨景', '注意边境证件要求', '秋季色彩最丰富'],
    suggestion: '适合慢住和边境风情体验。',
    liveTitle: '白哈巴村直播',
    liveHint: '可先看晨雾、云层和村庄热度。',
    liveKeyword: '白哈巴村 直播',
  }),
  createScenicSpot({
    id: 48,
    name: '木垒胡杨林',
    location: '新疆昌吉木垒',
    region: '昌吉',
    category: '胡杨湿地',
    rating: '4.6',
    longitude: 90.2864,
    latitude: 44.0168,
    description: '胡杨林与荒原气质兼具，秋色层次分明。',
    image: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    weather: { condition: '晴', temperature: '17°C', humidity: '34%', wind: '2级微风' },
    tips: ['秋天最适合前往', '适合长焦和逆光拍摄', '尽量避开大风天'],
    suggestion: '适合秋季摄影和昌吉周边自驾。',
    liveTitle: '木垒胡杨林直播',
    liveHint: '适合先看叶色和天气状态。',
    liveKeyword: '木垒胡杨林 直播',
  }),
  createScenicSpot({
    id: 49,
    name: '天山大峡谷',
    location: '新疆乌鲁木齐县',
    region: '乌鲁木齐周边',
    category: '峡谷地貌',
    rating: '4.6',
    longitude: 87.6287,
    latitude: 43.3616,
    description: '峡谷、林地和山间水系兼具，是乌鲁木齐周边热门短途景区。',
    image: 'https://bkimg.cdn.bcebos.com/pic/574e9258d109b3de9c82ea619ee47b81800a19d8e63d?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '晴', temperature: '18°C', humidity: '41%', wind: '2级山风' },
    tips: ['适合周末当天往返', '带防晒和轻外套', '适合家庭轻徒步'],
    suggestion: '适合乌鲁木齐近郊休闲和山地短线出游。',
    liveTitle: '天山大峡谷直播',
    liveHint: '可先看天气和道路情况。',
    liveKeyword: '天山大峡谷 直播',
  }),
  createScenicSpot({
    id: 50,
    name: '南山牧场',
    location: '新疆乌鲁木齐县',
    region: '乌鲁木齐周边',
    category: '草原森林',
    rating: '4.5',
    longitude: 87.3598,
    latitude: 43.4756,
    description: '草坡、松林和山野度假氛围浓厚，是乌鲁木齐人的经典周末景区。',
    image: 'https://bkimg.cdn.bcebos.com/pic/29381f30e924b8998593a8f862061d950b7bf647?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '多云', temperature: '16°C', humidity: '46%', wind: '2级山地风' },
    tips: ['适合露营和短住', '早晚温差明显', '周末人流较多'],
    suggestion: '适合近郊休闲和家庭轻出游。',
    liveTitle: '南山牧场直播',
    liveHint: '可先看草场天气和周末热度。',
    liveKeyword: '南山牧场 直播',
  }),
  createScenicSpot({
    id: 51,
    name: '博格达峰观景区',
    location: '新疆阜康',
    region: '乌鲁木齐周边',
    category: '湖泊雪山',
    rating: '4.6',
    longitude: 88.1035,
    latitude: 43.9064,
    description: '雪峰轮廓清晰，适合和天池线路联动看天山山体结构。',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    weather: { condition: '晴', temperature: '12°C', humidity: '38%', wind: '3级山风' },
    tips: ['晴天视野更好', '清晨更容易见到主峰轮廓', '适合长焦拍雪山'],
    suggestion: '适合雪山观景和天池周边补充游。',
    liveTitle: '博格达峰观景直播',
    liveHint: '适合确认能见度和云层变化。',
    liveKeyword: '博格达峰 直播',
  }),
  createScenicSpot({
    id: 52,
    name: '木特塔尔沙漠公园',
    location: '新疆和田洛浦',
    region: '和田',
    category: '沙漠峡谷',
    rating: '4.4',
    longitude: 80.0912,
    latitude: 37.1008,
    description: '和田一带的沙漠体验点，适合感受南疆边缘沙海风景。',
    image: 'https://images.unsplash.com/photo-1472396961693-142e6e269027?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    weather: { condition: '晴热', temperature: '31°C', humidity: '12%', wind: '3级偏东风' },
    tips: ['注意高温和补水', '适合日落时段体验', '建议跟景区项目走'],
    suggestion: '适合和田线路中的轻沙漠项目体验。',
    liveTitle: '和田沙漠公园直播',
    liveHint: '可先看风沙和日落状态。',
    liveKeyword: '和田沙漠 直播',
  }),
  createScenicSpot({
    id: 53,
    name: '尼雅遗址展示区',
    location: '新疆和田民丰',
    region: '和田',
    category: '古城人文',
    rating: '4.3',
    longitude: 82.7208,
    latitude: 37.0914,
    description: '承载精绝古国历史想象，是南疆深线很有辨识度的人文点。',
    image: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    weather: { condition: '晴', temperature: '28°C', humidity: '18%', wind: '2级热风' },
    tips: ['适合对西域历史感兴趣的人', '路线较远需预留时间', '建议提前了解背景故事'],
    suggestion: '适合深度南疆历史线用户。',
    liveTitle: '尼雅遗址周边直播',
    liveHint: '适合先看天气和现场开放状态。',
    liveKeyword: '尼雅遗址 直播',
  }),
  createScenicSpot({
    id: 54,
    name: '和田团城',
    location: '新疆和田市',
    region: '和田',
    category: '城市夜游',
    rating: '4.4',
    longitude: 79.9228,
    latitude: 37.1143,
    description: '老街更新后更适合漫游，能体验南疆城市日常生活与夜色。',
    image: 'https://images.unsplash.com/photo-1494526585095-c41746248156?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    weather: { condition: '晴', temperature: '26°C', humidity: '24%', wind: '2级微风' },
    tips: ['晚上更有氛围', '适合边走边吃', '适合轻松逛街拍照'],
    suggestion: '适合和田市区半日游和夜游。',
    liveTitle: '和田团城直播',
    liveHint: '可先看街区热度和夜景状态。',
    liveKeyword: '和田团城 直播',
  }),
  createScenicSpot({
    id: 55,
    name: '博乐河谷湿地',
    location: '新疆博州博乐',
    region: '博州',
    category: '胡杨湿地',
    rating: '4.4',
    longitude: 82.0593,
    latitude: 44.9049,
    description: '河谷湿地与城市边缘景观结合，适合轻松看水岸和候鸟。',
    image: 'https://bkimg.cdn.bcebos.com/pic/caef76094b36acaf51264a5b72d98d1000e99c57?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '晴', temperature: '19°C', humidity: '47%', wind: '2级河风' },
    tips: ['清晨适合看鸟和拍倒影', '适合亲子散步', '安排1到2小时即可'],
    suggestion: '适合作为赛里木湖周边补充休闲点。',
    liveTitle: '博乐河谷湿地直播',
    liveHint: '适合先看水面风况和天气。',
    liveKeyword: '博乐湿地 直播',
  }),
  createScenicSpot({
    id: 56,
    name: '精河木特塔尔胡杨林',
    location: '新疆博州精河',
    region: '博州',
    category: '胡杨湿地',
    rating: '4.5',
    longitude: 82.8861,
    latitude: 44.6784,
    description: '秋季胡杨黄叶和河岸线条结合，适合博州秋季自驾。',
    image: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    weather: { condition: '晴', temperature: '17°C', humidity: '35%', wind: '2级微风' },
    tips: ['秋色最适合打卡', '适合逆光拍摄', '尽量选择晴天'],
    suggestion: '适合秋季胡杨轻摄影和短途自驾。',
    liveTitle: '精河胡杨林直播',
    liveHint: '可先看叶色和天气。',
    liveKeyword: '精河胡杨林 直播',
  }),
  createScenicSpot({
    id: 57,
    name: '克孜尔石窟',
    location: '新疆阿克苏拜城',
    region: '阿克苏',
    category: '古城人文',
    rating: '4.7',
    longitude: 82.9588,
    latitude: 41.7816,
    description: '中国早期佛教石窟代表之一，适合深入了解龟兹文化。',
    image: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    weather: { condition: '晴', temperature: '25°C', humidity: '24%', wind: '2级微风' },
    tips: ['建议配讲解参观', '部分洞窟开放有限', '适合和库车人文线串联'],
    suggestion: '适合历史、壁画和佛教艺术爱好者。',
    liveTitle: '克孜尔石窟周边直播',
    liveHint: '可先看当日开放和客流情况。',
    liveKeyword: '克孜尔石窟 直播',
  }),
  createScenicSpot({
    id: 58,
    name: '托木尔大峡谷',
    location: '新疆阿克苏温宿',
    region: '阿克苏',
    category: '沙漠峡谷',
    rating: '4.7',
    longitude: 79.1863,
    latitude: 41.4546,
    description: '红色岩层与大峡谷地貌冲击强烈，是温宿线路代表性景区。',
    image: 'https://images.unsplash.com/photo-1464823063530-08f10ed1a2dd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    weather: { condition: '晴', temperature: '28°C', humidity: '19%', wind: '3级峡谷风' },
    tips: ['适合晴天前往', '穿防滑鞋更稳妥', '注意景区开放时段'],
    suggestion: '适合阿克苏地貌型自驾路线。',
    liveTitle: '托木尔大峡谷直播',
    liveHint: '适合先看光影和天气。',
    liveKeyword: '托木尔大峡谷 直播',
  }),
  createScenicSpot({
    id: 59,
    name: '塔里木胡杨林公园',
    location: '新疆阿拉尔',
    region: '阿拉尔',
    category: '胡杨湿地',
    rating: '4.6',
    longitude: 81.3386,
    latitude: 40.5609,
    description: '胡杨林、河道和秋色相互映衬，是南疆秋季热门观景点。',
    image: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    weather: { condition: '晴', temperature: '20°C', humidity: '27%', wind: '2级河风' },
    tips: ['秋季最值得前往', '适合观景车+步行结合', '逆光更有层次'],
    suggestion: '适合秋景摄影和胡杨主题旅行。',
    liveTitle: '塔里木胡杨林直播',
    liveHint: '适合先看叶色和天气。',
    liveKeyword: '塔里木胡杨林 直播',
  }),
  createScenicSpot({
    id: 60,
    name: '塔河源景区',
    location: '新疆阿拉尔',
    region: '阿拉尔',
    category: '胡杨湿地',
    rating: '4.3',
    longitude: 81.2861,
    latitude: 40.5475,
    description: '河岸湿地与绿洲景观结合，适合城市周边休闲看水。',
    image: 'https://images.unsplash.com/photo-1439066615861-d1af74d74000?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    weather: { condition: '晴', temperature: '22°C', humidity: '33%', wind: '2级微风' },
    tips: ['适合傍晚散步', '适合亲子和老人', '安排半日即可'],
    suggestion: '适合阿拉尔城市休闲游。',
    liveTitle: '塔河源直播',
    liveHint: '可先看水面和当日天气。',
    liveKeyword: '塔河源 直播',
  }),
  createScenicSpot({
    id: 61,
    name: '白杨沟景区',
    location: '新疆昌吉呼图壁',
    region: '昌吉',
    category: '峡谷地貌',
    rating: '4.4',
    longitude: 86.7185,
    latitude: 43.7778,
    description: '山谷林地和溪流环境比较清爽，是昌吉近郊热门短线景区。',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    weather: { condition: '多云', temperature: '17°C', humidity: '44%', wind: '2级山风' },
    tips: ['适合周末当天往返', '穿运动鞋更舒服', '适合夏季避暑'],
    suggestion: '适合近郊轻徒步和家庭休闲。',
    liveTitle: '白杨沟景区直播',
    liveHint: '适合先看山里天气。',
    liveKeyword: '白杨沟 直播',
  }),
  createScenicSpot({
    id: 62,
    name: '玛纳斯国家湿地公园',
    location: '新疆昌吉玛纳斯',
    region: '昌吉',
    category: '胡杨湿地',
    rating: '4.4',
    longitude: 86.1877,
    latitude: 44.3295,
    description: '湿地候鸟资源丰富，适合亲子自然观察和轻休闲散步。',
    image: 'https://bkimg.cdn.bcebos.com/pic/caef76094b36acaf51264a5b72d98d1000e99c57?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70',
    weather: { condition: '晴', temperature: '19°C', humidity: '48%', wind: '2级微风' },
    tips: ['清晨适合观鸟', '适合带孩子认识湿地生态', '安排半日较合适'],
    suggestion: '适合昌吉方向的自然轻游。',
    liveTitle: '玛纳斯湿地直播',
    liveHint: '可先看天气和水面状况。',
    liveKeyword: '玛纳斯湿地 直播',
  }),
  createScenicSpot({
    id: 63,
    name: '平定准噶尔勒铭格登山碑',
    location: '新疆昌吉奇台',
    region: '昌吉',
    category: '古城人文',
    rating: '4.3',
    longitude: 89.5932,
    latitude: 44.0226,
    description: '清代平定准噶尔的重要纪功碑之一，位置相对小众，适合对新疆边疆史和碑刻遗存感兴趣的游客。',
    image: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    weather: { condition: '晴', temperature: '18°C', humidity: '36%', wind: '2级微风' },
    tips: ['更适合顺路探访，建议提前确认现场可达性', '适合结合奇台或昌吉历史线路一起看', '对碑刻和清代边疆史感兴趣会更有收获'],
    suggestion: '适合小众历史点打卡和新疆地方史深度游。',
    liveTitle: '格登山碑周边实况',
    liveHint: '该点更偏历史遗存，建议出发前确认天气与路况。',
    liveKeyword: '格登山碑 奇台',
  }),
  createScenicSpot({
    id: 64,
    name: '吐峪沟石窟与麻扎村',
    location: '新疆吐鲁番鄯善',
    region: '吐鲁番',
    category: '古城人文',
    rating: '4.5',
    longitude: 89.4283,
    latitude: 42.8575,
    description: '兼具佛教石窟、古村聚落和峡谷绿洲气质，是吐鲁番较有历史层次感的小众人文点。',
    image: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    weather: { condition: '晴', temperature: '29°C', humidity: '18%', wind: '2级微风' },
    tips: ['适合搭配高昌故城或火焰山线路', '建议慢走看村落细节', '对宗教遗存和聚落史更有感觉的人会更喜欢'],
    suggestion: '适合吐鲁番深度人文半日游。',
    liveTitle: '吐峪沟周边实况',
    liveHint: '更适合看天气和现场通达情况。',
    liveKeyword: '吐峪沟 麻扎村',
  }),
  createScenicSpot({
    id: 65,
    name: '惠远古城钟鼓楼片区',
    location: '新疆伊犁霍城',
    region: '伊犁',
    category: '古城人文',
    rating: '4.4',
    longitude: 80.8784,
    latitude: 44.0352,
    description: '保留清代伊犁将军府城历史记忆，适合了解伊犁边疆治理与古城格局。',
    image: 'https://images.unsplash.com/photo-1494526585095-c41746248156?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    weather: { condition: '晴', temperature: '22°C', humidity: '35%', wind: '2级微风' },
    tips: ['适合与霍城薰衣草或伊犁河谷线路搭配', '建议配合历史背景一起看', '古城氛围偏安静，适合慢逛'],
    suggestion: '适合伊犁线中的小众清代边疆史打卡。',
    liveTitle: '惠远古城周边实况',
    liveHint: '适合先看天气与古城街区状态。',
    liveKeyword: '惠远古城 霍城',
  }),
  createScenicSpot({
    id: 66,
    name: '靖远寺',
    location: '新疆伊犁霍城惠远镇',
    region: '伊犁',
    category: '古城人文',
    rating: '4.4',
    longitude: 80.8851,
    latitude: 44.0341,
    description: '伊犁地区颇具代表性的藏传佛教寺院遗存之一，适合串联惠远古城一线看边疆宗教文化。',
    image: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    weather: { condition: '晴', temperature: '21°C', humidity: '37%', wind: '2级微风' },
    tips: ['适合和惠远古城一起安排', '保持安静更适合参观寺院空间', '对清代伊犁历史感兴趣会更有收获'],
    suggestion: '适合边疆宗教文化与清代伊犁史主题游。',
    liveTitle: '靖远寺周边实况',
    liveHint: '建议先看天气与现场开放状态。',
    liveKeyword: '靖远寺 惠远',
  }),
  createScenicSpot({
    id: 67,
    name: '阿克苏文庙',
    location: '新疆阿克苏市',
    region: '阿克苏',
    category: '古城人文',
    rating: '4.3',
    longitude: 80.2639,
    latitude: 41.1714,
    description: '阿克苏市区内较少被旅行者专门停留的历史遗存，适合补充看南疆城市里的传统礼制建筑线索。',
    image: 'https://images.unsplash.com/photo-1494526585095-c41746248156?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    weather: { condition: '晴', temperature: '27°C', humidity: '22%', wind: '2级微风' },
    tips: ['适合与库车或阿克苏市区人文点一起安排', '更适合历史向游客', '停留时间不用太长但适合细看'],
    suggestion: '适合南疆城市历史脉络补充型打卡。',
    liveTitle: '阿克苏文庙周边实况',
    liveHint: '出发前建议确认开放情况。',
    liveKeyword: '阿克苏文庙',
  }),
]

export const scenicCategories = ['全部', ...new Set(destinationList.map((item) => item.category))]

const regionOrder = [
  '乌鲁木齐市',
  '克拉玛依市',
  '吐鲁番市',
  '昌吉州',
  '博州',
  '巴州',
  '阿克苏地区',
  '喀什地区',
  '和田地区',
  '伊犁州',
  '塔城地区',
  '阿勒泰地区',
]

export const scenicRegions = ['全部', ...regionOrder.filter((item) => destinationList.some((spot) => spot.region === item))]

const destinationCultureMap = {
  1: {
    overview: '天山天池位于博格达峰北麓，是新疆最具代表性的高山湖泊景区之一，湖水、雪峰、云杉林和山地步道共同构成了经典的天山风光。',
    history: '天池古称“瑶池”，在中国传统神话里常被附会为西王母宴游之地。清代以来，这里逐渐被纳入新疆山岳湖泊名胜体系，后来成为近现代新疆旅游开发最早的一批核心景区。',
    highlights: '适合把神话意象、雪山湖泊和家庭轻观光放在同一条线路里理解，也是很多游客认识新疆山地景观的第一站。',
  },
  2: {
    overview: '喀纳斯景区位于阿勒泰深山林区，以高山湖泊、针叶林、河谷、图瓦村落和四季分明的色彩变化著称，是北疆自然景观的代表。',
    history: '喀纳斯长期是阿尔泰山游牧、狩猎与山地交通活动的区域，周边图瓦人聚落保留了独特生活方式。近几十年随着生态旅游发展，喀纳斯逐渐从边远山地目的地成长为全国知名的自然风景区。',
    highlights: '它不只是看一片湖，更重要的是湖区、村落、白桦林和山地文化共同构成的完整北疆风景系统。',
  },
  3: {
    overview: '赛里木湖位于新疆西部高原盆地边缘，湖面开阔，周边雪山、草场和天光变化明显，是伊犁与博州一线极具代表性的湖泊景观。',
    history: '赛里木湖常被称作“大西洋最后一滴眼泪”，这一名称来自它所处的西风影响地带和高原湖泊意象。历史上这里也是西天山交通与草场活动的重要区域，近现代逐步发展为新疆经典环湖自驾目的地。',
    highlights: '比起单点打卡，赛里木湖更适合从“环湖”视角去体验，历史上的通道感和今天的公路旅行体验在这里连接得很自然。',
  },
  4: {
    overview: '白沙湖景区位于帕米尔高原公路沿线，白沙山、湖水、雪峰背景和高海拔通道景观共同形成了极具辨识度的画面。',
    history: '白沙湖所在区域长期是喀喇昆仑与帕米尔交通线的重要路段，历史上的商旅、使节和边地往来都曾经过这一带。今天游客熟悉的“白沙山白沙湖”景观，本质上是高原风沙堆积与山地湖泊共同作用形成的自然地貌。',
    highlights: '这里最值得理解的是“路上的风景”意义，它不仅是一个湖，更是帕米尔公路旅行情绪和节奏的重要开场。',
  },
  5: {
    overview: '那拉提草原位于伊犁河谷东部山地，是新疆最有名的高山草原景区之一，牧场、雪岭、河谷和空中草原层次丰富。',
    history: '那拉提一带自古就是游牧活动区域，哈萨克牧民的转场传统和草原生活方式深深影响了这里的景观气质。近现代随着伊犁草原旅游的发展，那拉提逐渐成为新疆草原意象最典型的代表之一。',
    highlights: '相比只看一片草地，那拉提更适合从“游牧草原文化”和“天山立体牧场景观”两个角度去体会。',
  },
  7: {
    overview: '巴音布鲁克景区位于天山腹地高寒草原区，以开阔草场、湿地河曲和九曲十八弯落日景观闻名。',
    history: '巴音布鲁克在蒙古语中常被解释为“丰富的泉水”，其形成与高山盆地水系和草原湿地环境密切相关。这里长期是重要牧场区域，后来随着独库公路和草原旅游线路成熟，成为新疆草原与落日摄影的标志性目的地。',
    highlights: '它的魅力不只在一个观景台，而在“高山草原+湿地水系+傍晚光线”共同构成的辽阔感。',
  },
  8: {
    overview: '禾木景区以木屋村落、白桦林、河谷晨雾和山地草坡闻名，是阿勒泰地区最具童话感的目的地之一。',
    history: '禾木一带与图瓦人聚居历史相关，村落格局、木屋样式和生活方式保留了明显的山地聚落特色。随着北疆生态旅游和摄影旅行兴起，禾木逐渐从边远村落变成全国知名的秋季风景地。',
    highlights: '这里最值得看的其实是“村落与自然的关系”，晨雾、木屋和白桦林一起才构成完整的禾木气质。',
  },
  9: {
    overview: '喀什古城是南疆最具辨识度的人文景区之一，街巷肌理、土建筑风貌、巴扎生活和多民族交流氛围共同构成了古城魅力。',
    history: '喀什自古就是丝绸之路上的重镇，连接中亚、南亚与西域腹地。古城片区长期承担商贸、手工业与居民生活功能，因此它的历史价值不仅在建筑本身，也在持续延续的城市生活传统。',
    highlights: '这里适合把“老城街巷”“手工艺”“夜市”和“丝路商贸记忆”放在一起看，会比单纯拍照更有意思。',
  },
  10: {
    overview: '交河故城位于吐鲁番盆地，是中国现存保存较完整的大型生土古城遗址之一，城址布局和残存街巷仍能看出古代都市结构。',
    history: '交河故城始建较早，曾是古代车师前国的重要都城，后又成为高昌地区的重要军事与交通节点。因为地处丝绸之路干线附近，它在西域政权更替、商旅往来和佛教传播过程中都占有重要位置。',
    highlights: '相比一般古迹，交河故城最值得看的是遗址本身保存下来的空间秩序，能直观感受到古代西域城市的规模和组织方式。',
  },
  11: {
    overview: '坎儿井民俗园集中展示了吐鲁番绿洲灌溉智慧，是理解当地为何能在火洲环境中形成农业文明的重要窗口。',
    history: '坎儿井系统是新疆绿洲社会极具代表性的地下引水工程，依靠暗渠、竖井和地势落差把山前潜流引入耕地与聚落。它凝结了长期因地制宜的水利经验，也支撑了吐鲁番历史上的农业、聚落和商旅补给。',
    highlights: '看坎儿井时最好把它当成“工程文明遗产”来看，而不只是一个景点，它解释了吐鲁番很多历史现象的基础。',
  },
  12: {
    overview: '库车王府是阿克苏库车地区很有代表性的历史建筑景点，兼具地方政权记忆、居住空间和民俗展示功能。',
    history: '库车古称龟兹，是西域历史文化重镇。今天游客看到的王府与晚近时期地方行政和王公家族活动相关，也承接了库车作为南疆交通节点和文化汇聚地的城市历史。',
    highlights: '如果和库车老城、克孜尔石窟一起看，会更容易理解龟兹文化从宗教艺术到城市生活的连续性。',
  },
  13: {
    overview: '库木塔格沙漠位于鄯善城区边缘，是少见的“城市紧贴沙漠”景观，黄沙、绿洲和城镇边界关系非常鲜明。',
    history: '库木塔格名字本身就带有典型的西域地理色彩，这片沙漠与吐鲁番盆地东缘的风沙堆积环境紧密相关。它所在区域历史上既受丝路交通影响，也长期体现着绿洲与沙海对峙的生存格局。',
    highlights: '这里最特别的不是沙漠本身有多极端，而是城市、绿洲和沙丘几乎无缝衔接的反差感。',
  },
  14: {
    overview: '天山神秘大峡谷是库车地区最著名的红层峡谷景观之一，峡壁高耸、色彩浓烈、通道曲折，视觉冲击很强。',
    history: '峡谷形成于长期风化与流水切割作用，所展现的红色岩层也和库车一带复杂的地质构造有关。它所在区域与古龟兹文化圈距离不远，因此常被放进“库车自然地貌+丝路人文”组合线路里一起体验。',
    highlights: '适合把它理解成南疆地貌代表作之一，和库车的人文古迹形成很强反差。',
  },
  15: {
    overview: '乌尔禾魔鬼城是准噶尔盆地西北缘著名雅丹地貌区，风蚀残丘广布，形态奇诡，特别适合看日落和荒野感画面。',
    history: '“魔鬼城”的名字来自强风穿过雅丹地貌时产生的呼啸声，也反映了人们对这种荒凉奇观的早期直观感受。近现代随着影视作品传播和公路旅行兴起，这里逐渐成为新疆地貌景观的代表名片。',
    highlights: '如果想理解“西部荒原感”为什么这么有冲击力，乌尔禾魔鬼城是很好的实景教材。',
  },
  16: {
    overview: '塔克拉玛干沙漠是塔里木盆地核心区域的超级沙海景观，沙丘尺度巨大、地表起伏延绵，是新疆荒漠意象最强烈的地方之一。',
    history: '塔克拉玛干长期存在于丝路南北道的地理叙事中，古代绿洲城市和商旅通道大多绕沙漠边缘分布。它不只是自然景观，也深刻影响了南疆聚落、交通和文明布局。',
    highlights: '看塔克拉玛干时，最值得感受的是“沙海如何定义绿洲文明边界”。',
  },
  17: {
    overview: '泽普金湖杨景区以胡杨、湿地、水岸和秋色层次见长，是喀什地区较受欢迎的秋季轻休闲景区。',
    history: '金湖杨所展现的是叶尔羌河流域典型的绿洲边缘生态景观，胡杨林与河岸水系共同塑造了南疆秋色记忆。它也反映了南疆很多地区“河流决定景观”的生态规律。',
    highlights: '如果想看南疆更柔和、适合慢走的秋景，这里是很好的代表。',
  },
  18: {
    overview: '轮台胡杨林公园是塔里木河流域重要的胡杨观赏地之一，秋季金黄树冠与河道湿地共同构成很强的视觉记忆。',
    history: '轮台一带长期处于塔里木河生态带影响之下，胡杨林因此成为当地最有代表性的自然符号之一。随着秋季摄影旅游兴起，这里逐渐成为新疆胡杨主题线路中的核心节点。',
    highlights: '这里最适合从“河流生态带”角度理解胡杨，而不只是把它当一片黄叶林。',
  },
  19: {
    overview: '博斯腾湖是新疆重要的大型内陆淡水湖之一，湖面开阔、芦苇湿地丰富，同时兼具休闲旅游和亲水体验属性。',
    history: '博斯腾湖与焉耆盆地水系和绿洲农业关系密切，历史上不仅影响区域生态，也影响周边聚落发展与渔业活动。近现代旅游开发后，它逐渐成为巴州较成熟的湖泊休闲景区。',
    highlights: '相比高山湖泊的壮阔，它更偏向“绿洲湖区生活感”和家庭休闲属性。',
  },
  20: {
    overview: '可可托海景区融合了峡谷河流、白桦林、花岗岩山体和矿业遗址，是阿勒泰地区兼具自然与工业记忆的独特景区。',
    history: '可可托海不仅有自然景观，也承载着新中国矿业开发的重要历史记忆，尤其与稀有金属矿开采和工业建设有关。它因此常被认为是新疆少有的“风景与工业史并存”的目的地。',
    highlights: '这里适合同时看自然风景和矿业历史，气质会比单纯山水景区更厚重。',
  },
  21: {
    overview: '江布拉克景区位于天山北麓山地农业与草原过渡带，麦田、林带、山谷与远山轮廓共同构成很有层次的田园景观。',
    history: '江布拉克所在区域体现了新疆农牧交错地带的景观特征，山地农业、牧场和交通线长期共同塑造了这片区域的面貌。近年它因麦浪、公路和轻摄影氛围而被更多游客认识。',
    highlights: '这里适合看“田野与山地”如何叠加，而不是单纯当作一个草原景区。',
  },
  22: {
    overview: '帕米尔旅游区覆盖塔县及周边高原公路风景带，雪峰、湖泊、河谷、边境风情和高原村落共同构成了大尺度景观。',
    history: '帕米尔自古就是中亚与南疆之间的重要通道，历史上商旅、使节、驻防和边地交流都与这里密切相关。现代游客走的公路，在很大程度上也延续了这片高原“交通走廊”的历史属性。',
    highlights: '理解帕米尔最好的方式不是只盯一个点，而是把它看成一条有历史深度的高原风景线路。',
  },
  23: {
    overview: '国际大巴扎是乌鲁木齐极具标志性的城市地标，集市、餐饮、手工艺和建筑意象汇聚，适合快速感受城市烟火气。',
    history: '“巴扎”在新疆城市文化中长期意味着交易、社交和日常生活交汇的公共空间。国际大巴扎是在现代城市建设背景下形成的集中展示区，但其文化意义仍然延续了传统巴扎的商业与交流属性。',
    highlights: '它不是传统古迹，却是理解现代新疆城市商业文化和游客体验逻辑的重要场景。',
  },
  24: {
    overview: '葡萄沟景区以绿洲水系、葡萄种植和庭院民俗体验著称，是吐鲁番最经典的休闲类景区之一。',
    history: '吐鲁番盆地依靠坎儿井灌溉和绿洲农业形成了闻名的葡萄文化，葡萄沟正是这一农业文明最直观的展示区域。它既体现了自然条件的严酷，也体现了绿洲居民长期经营水土的能力。',
    highlights: '游葡萄沟时，如果能把葡萄、庭院和坎儿井水利联系起来看，会更能理解吐鲁番“火洲绿洲”的由来。',
  },
  25: {
    overview: '卡拉库里湖位于慕士塔格峰脚下，是帕米尔公路线上最经典的高原湖泊景观点之一。',
    history: '这片湖区长期属于帕米尔交通通道上的自然地标，雪峰、湖泊与牧场共同定义了高原旅行的视觉记忆。卡拉库里湖之所以广为人知，也和现代公路旅行让它更容易被看见有关。',
    highlights: '它最大的价值在于“雪峰倒影+高原公路”这个极具帕米尔辨识度的组合。',
  },
  26: {
    overview: '慕士塔格冰川公园以雪峰、冰川和高原山地景观为核心，是帕米尔线上最具高海拔视觉冲击的自然景区之一。',
    history: '慕士塔格峰长期是帕米尔高原地理认知中的重要坐标，其冰川与雪山景观也一直影响着周边公路旅行和高原探险叙事。现代景区开发使更多游客能够近距离接触这类高山冰川景观。',
    highlights: '如果想感受帕米尔的“高度感”和冰川尺度，这里比普通观景点更直接。',
  },
  27: {
    overview: '昭苏湿地公园把湿地、花海、草场与天马文化线路连接起来，是伊犁夏季比较轻盈的自然景观目的地。',
    history: '昭苏地区长期以草原和马文化著称，湿地景观则进一步丰富了当地夏季自然资源类型。它在现代旅游线路里常与油菜花、草原和天马活动一起出现。',
    highlights: '这里适合从“夏季昭苏风貌”整体去看，而不是只盯单一景观。',
  },
  28: {
    overview: '夏塔景区集合雪山、河谷、草原和古道遗迹，是伊犁兼具自然大景和历史通道意味的代表线路。',
    history: '夏塔古道在历史上是连接天山南北的重要通行路线之一，也因此带有明显的古道文化记忆。今天游客看到的步道和雪山风景，背后仍能感受到这条古交通线的历史痕迹。',
    highlights: '这里的独特之处在于“古道感”，风景之外还自带一种历史行旅氛围。',
  },
  29: {
    overview: '特克斯八卦城是伊犁州极具辨识度的县城地标，以放射状道路和城市格局闻名，适合看城市布局与县城生活。',
    history: '特克斯八卦城的规划常被与传统方位观念和八卦意象联系在一起，现代城市形态因此拥有鲜明记忆点。它既是功能性县城，也因为独特布局而成为新疆少见的“城市格局型景点”。',
    highlights: '这里最值得看的是整体布局概念，而不是单体建筑，俯瞰视角会比步行更能体现它的特色。',
  },
  30: {
    overview: '高昌故城是吐鲁番地区规模宏大的古城遗址，与交河故城一起构成新疆东天山南麓极重要的丝路历史板块。',
    history: '高昌在古代西域历史中占据重要位置，曾长期作为区域政治、商业和佛教文化中心之一。因为位于丝路要冲，高昌故城见证了多民族、多政权和多宗教在西域交汇发展的过程。',
    highlights: '如果想系统了解吐鲁番古城文明，高昌故城和交河故城最好放在一条人文线里一起看。',
  },
  31: {
    overview: '火焰山景区以连绵赤红山体和极端热感形象著称，是吐鲁番最广为人知的自然地标之一。',
    history: '火焰山在地理上属于典型的干热荒漠地貌景观，而在文化传播上又因《西游记》的经典叙事而拥有极高知名度。现实地貌与文学想象在这里叠加，使它成为新疆少见的“地理与文化双重符号”。',
    highlights: '它更适合被看作吐鲁番气候与文化意象的象征，而不只是一个短时打卡点。',
  },
  32: {
    overview: '温宿大峡谷以红层峡谷、断崖和层理地貌为特色，是阿克苏地区非常有代表性的地貌型景区。',
    history: '这片峡谷的景观形成与长期地质构造抬升、风化和流水切割密切相关，也因此成为新疆西部红层地貌的重要展示区。随着自驾旅游普及，它逐渐成为阿克苏地貌名片之一。',
    highlights: '如果喜欢“纯地貌张力”，温宿大峡谷是南疆非常典型的一站。',
  },
  33: {
    overview: '罗布人村寨把胡杨、塔里木河、沙漠与民俗展示结合在一起，是巴州兼具景观和文化气息的复合型景区。',
    history: '“罗布人”所承载的是塔里木河流域边缘居民的生活记忆，围绕河流、渔猎、胡杨和沙地环境形成了鲜明地方特征。景区化展示让游客更容易从一个点理解河流与人群的关系。',
    highlights: '这里的核心不是某一栋建筑，而是“水、林、沙、人”四者如何组合。',
  },
  34: {
    overview: '天鹅河景区是库尔勒城市水系和湿地景观的代表，适合看城市滨水生活和夜景氛围。',
    history: '库尔勒城市发展与水系治理长期相关，天鹅河景区则体现了现代城市与水环境共建后的景观成果。它更多代表当代城市休闲文化，而不是传统古迹型景区。',
    highlights: '这类景区的价值在“城市生活感”，很适合补充南疆大景之外的日常面向。',
  },
  35: {
    overview: '独库公路北段观景线串联雪山、草场、峡谷和高山公路，是新疆公路旅行最经典的风景线路之一。',
    history: '独库公路具有鲜明的现代交通建设历史意义，它极大缩短了南北疆之间的通行距离，也因此在新疆地理认知中拥有特殊地位。如今它既是一条交通通道，也是一条带有时代记忆的风景公路。',
    highlights: '独库的价值在“路”本身，沿途不断切换的地貌和交通工程意义共同构成它的魅力。',
  },
  38: {
    overview: '新疆博物馆是了解新疆历史、民族文化和丝绸之路文明最系统的公共文化场馆之一。',
    history: '博物馆通过考古文物、历史文献和专题展览，呈现了新疆从古代西域到近现代的发展脉络。很多游客把它作为入疆第一站，正是因为它能为后续看古城、石窟、草原和绿洲提供背景框架。',
    highlights: '如果行程里有人文内容，新疆博物馆很适合作为“先补课再出发”的总入口。',
  },
  39: {
    overview: '红山公园是乌鲁木齐城市中心极具代表性的地标型公园，高点视野和城市轮廓观赏价值很突出。',
    history: '红山在乌鲁木齐城市记忆中占据重要位置，不仅是地貌标志，也长期参与城市公共生活和地方形象构建。很多本地人对乌鲁木齐的认知，都离不开红山这一象征性空间。',
    highlights: '它最适合从“城市地标”而非传统景区角度理解。',
  },
  40: {
    overview: '达坂城古镇把边塞意象、风车景观和周边通道文化结合起来，是乌鲁木齐周边较有辨识度的短途目的地。',
    history: '达坂城长期与交通关口、边地通道和歌谣文化联系在一起，在新疆流行文化叙事中也有较高辨识度。今天的古镇体验虽然偏旅游化，但仍延续了这一地区的边塞印象。',
    highlights: '这里更像一个“新疆边塞印象窗口”，适合短时间感受地域氛围。',
  },
  41: {
    overview: '果子沟大桥观景台位于伊犁交通咽喉地带，桥梁工程、山谷地形与森林牧坡同框，是很典型的现代新疆公路景观。',
    history: '果子沟自古就是伊犁交通要道之一，历史上商旅和军政往来都要经过这条山口通道。现代大桥的建成则让这条古老通道拥有了新的工程地标意义。',
    highlights: '这里最有意思的是“古通道+现代桥梁”的叠加感，很适合放在伊犁自驾叙事里理解。',
  },
  42: {
    overview: '霍城薰衣草庄园以花田景观和伊犁河谷夏季色彩闻名，是近年来很受欢迎的轻摄影型景区。',
    history: '霍城所处的伊犁河谷气候条件适合薰衣草种植，这种经济作物后来逐渐转化为当地重要的观光资源。它体现的是现代农业与旅游结合后形成的新景观。',
    highlights: '它虽然没有深厚古代历史，但很能代表今天伊犁夏季旅游的轻盈一面。',
  },
  43: {
    overview: '琼库什台是伊犁地区保存较好的一类原生态山地村落，草坡、木屋、河谷和牧道共同构成很强的边地感。',
    history: '琼库什台长期与山地牧业和转场生活相关，村落形态也体现了高山草原居住环境的特点。近年随着徒步和慢旅行兴起，它从相对冷门的山村逐渐成为伊犁深度游的重要节点。',
    highlights: '它的吸引力在“慢”，住下来感受村落、草原和道路关系，会比快进快出更值得。',
  },
  45: {
    overview: '乌伦古湖是阿勒泰地区重要的湖泊景观之一，湖岸开阔、风力明显，适合安静看水面与落日变化。',
    history: '乌伦古湖与阿勒泰北部水系和区域生态环境联系紧密，在当地渔业与湖区生活中也具有长期意义。相比热门景区，它保留了更强的地方性与安静感。',
    highlights: '这里适合不赶景点、想看更松弛湖景的人。',
  },
  46: {
    overview: '五彩滩位于额尔齐斯河岸，是阿勒泰地区极具代表性的彩色丘陵与河岸复合景观。',
    history: '五彩滩的地貌层理来自长期风蚀、水蚀与沉积作用，河流与岸坡共同塑造了今天极具层次感的地表。它在近现代旅游传播中逐渐成为北疆“黄昏地貌摄影”代表点。',
    highlights: '这里最关键的是时间，傍晚的低角度光线几乎决定了五彩滩的表现力。',
  },
  47: {
    overview: '白哈巴村是阿勒泰边境线附近极具代表性的木屋村落之一，森林、山谷和边境气息让它有很强的静谧感。',
    history: '白哈巴与图瓦人聚落和边境山地生活方式相关，村庄的木屋、道路和生活节奏都带有明显边地特色。因为地理位置特殊，它也在新疆旅游地图上始终具有独特存在感。',
    highlights: '相比禾木，它更安静、更边境，也更适合住下来体会村落气质。',
  },
  48: {
    overview: '木垒胡杨林以秋季胡杨色彩和荒原背景为特色，是昌吉方向颇有辨识度的胡杨观赏地。',
    history: '木垒地区处在山前与荒漠过渡地带，胡杨林景观因此兼具苍劲和空旷感。它体现了新疆东部较为典型的干旱区树木景观特征。',
    highlights: '如果喜欢更粗粝、更安静的秋色，木垒胡杨林会很对味。',
  },
  49: {
    overview: '天山大峡谷是乌鲁木齐近郊很成熟的山地峡谷景区，林地、溪流、山谷和轻徒步线路结合得比较完整。',
    history: '它所在区域属于天山北坡山地休闲带的一部分，长期承担乌鲁木齐周边市民短途出游功能。虽然不是古迹型景点，但很能代表现代城市近郊休闲旅游的发展。',
    highlights: '适合把它当作“乌鲁木齐周边山地日常生活景观”来看。',
  },
  50: {
    overview: '南山牧场是乌鲁木齐人熟悉的近郊草原度假区域，草坡、松林和山地营地氛围很浓。',
    history: '南山一带长期与牧场、避暑和近郊度假活动联系在一起，也是乌鲁木齐城市外扩后最早形成大众周末休闲认知的区域之一。它在本地生活里有很强的日常性。',
    highlights: '比起远途大景，南山牧场更像乌鲁木齐城市生活的“后花园”。',
  },
  51: {
    overview: '博格达峰观景区适合从更直接的角度观察东天山主峰轮廓和山体结构，是天池周边重要的补充观景点。',
    history: '博格达峰在新疆山岳意象中一直具有很强代表性，也是天山天池神话和现实地理叙事的重要背景。围绕它形成的观景线路，让游客更容易把雪峰和湖泊放在同一套天山认知里。',
    highlights: '如果想把“天山”看得更具体，博格达峰是非常关键的视觉锚点。',
  },
  52: {
    overview: '木特塔尔沙漠公园是和田方向较容易接近的沙漠体验点，适合感受南疆边缘沙海与日落氛围。',
    history: '和田绿洲与沙漠长期相伴，沙海边缘景观本身就构成了当地生活与文化的背景。类似木特塔尔这样的景区，某种程度上让游客以更轻松方式接触这种绿洲边缘生态。',
    highlights: '它适合做和田线路里的“第一层沙漠体验”。',
  },
  53: {
    overview: '尼雅遗址展示区与精绝古国历史想象紧密相连，是和田深线极具辨识度的人文目的地。',
    history: '尼雅遗址所在区域与古代丝路南道绿洲文明关系密切，相关考古发现让人们重新认识了塔克拉玛干南缘古代聚落与商旅网络。它因此在西域考古与精绝文化讨论中占有特殊位置。',
    highlights: '这里适合带着“古国消失在沙海边缘”的想象去看，会更能体会它的人文重量。',
  },
  54: {
    overview: '和田团城是和田市区很有生活感的老街片区，适合看南疆城市街巷、夜色与日常烟火气。',
    history: '团城承接了和田老城区的生活空间记忆，街巷尺度和城市肌理里仍能感受到地方居住传统。经过更新之后，它也成为展示和田城市形象的重要窗口。',
    highlights: '这里最适合边走边看，把它当“南疆城市日常样本”会更有意思。',
  },
  55: {
    overview: '博乐河谷湿地是博州城市边缘较轻松的自然休闲点，水岸、湿地和候鸟元素让整体氛围更平和。',
    history: '这类河谷湿地景观与博州地区水系治理和城市边缘生态恢复关系紧密，更多体现的是现代生态空间建设。它为赛里木湖等大景观之外提供了更日常的自然体验。',
    highlights: '适合作为长线行程里的节奏放缓点。',
  },
  56: {
    overview: '精河木特塔尔胡杨林是博州方向较受欢迎的秋色景点，胡杨、河岸和金色叶片共同构成秋季短途自驾亮点。',
    history: '胡杨林的存在依赖干旱区河流生态带，这也让它成为理解新疆西部绿洲边缘景观的一个切口。随着秋景旅游流行，这里逐渐被纳入更多博州自驾线路。',
    highlights: '它更适合轻摄影和短线自驾，氛围安静、不算重景区。',
  },
  57: {
    overview: '克孜尔石窟是中国早期佛教石窟艺术的重要代表之一，也是理解龟兹文化的关键遗址。',
    history: '石窟开凿年代较早，曾是古代龟兹地区佛教传播和壁画艺术发展的重要中心。它在中西文化交流史上意义很大，因为许多艺术风格和题材都体现了丝绸之路文化交汇的特征。',
    highlights: '如果对新疆人文感兴趣，克孜尔石窟几乎是必须看的节点，它能把“龟兹”从地名变成具体可感的文化现场。',
  },
  58: {
    overview: '托木尔大峡谷是阿克苏地区红层峡谷的重要代表，地貌尺度大、层次丰富，画面感极强。',
    history: '它与温宿大峡谷一样，都是新疆西南部复杂地质与长期侵蚀作用的结果。作为景区名称中的“托木尔”，也让它与天山南麓更广阔的山地地理联系起来。',
    highlights: '如果偏爱“大开大合”的地貌风景，托木尔大峡谷非常直接。',
  },
  59: {
    overview: '塔里木胡杨林公园以大面积胡杨、河道和秋季色彩著称，是南疆胡杨主题旅行中的热门景区。',
    history: '胡杨林与塔里木河水系关系密切，它们共同构成了南疆绿洲边缘极具代表性的生态景观。人们之所以对胡杨有强烈情感，也与其在干旱环境中顽强生长、长期进入西域文学和影像表达有关。',
    highlights: '这里适合从生态和审美两个角度看：一面是生境系统，一面是秋色与树形带来的强烈视觉记忆。',
  },
  60: {
    overview: '塔河源景区以河岸湿地与绿洲环境为主，适合阿拉尔方向的城市周边休闲和慢节奏看水。',
    history: '名称里的“塔河”本身就提示了与塔里木河流域生态空间的联系。它更多体现的是现代城市周边生态景观的营造，而非传统古迹型历史。',
    highlights: '这种景区的价值在放松和补充体验，适合长线旅行中的轻量停留。',
  },
  61: {
    overview: '白杨沟景区是昌吉近郊较受欢迎的山谷溪流型景区，适合夏季短途避暑和轻徒步。',
    history: '白杨沟所在区域长期属于天山北坡近郊山地休闲带的一部分，随着城市周边旅游发展，它逐渐成为本地周末出游的经典选择。它更偏生活性景区，而非重历史景区。',
    highlights: '适合把它当作“近郊山谷呼吸站”，不用带太强的打卡心态。',
  },
  62: {
    overview: '玛纳斯国家湿地公园以湿地、水鸟和开阔生态环境为主，是昌吉方向兼具自然观察与家庭休闲属性的景区。',
    history: '湿地公园代表的是现代生态保护与科普展示理念，体现了当地在水域、生境和鸟类资源保护上的持续投入。它的“历史”更多来自生态治理与保护实践，而不是古代遗址脉络。',
    highlights: '很适合亲子和轻科普旅行，尤其适合作为节奏缓一点的自然观察点。',
  },
  63: {
    overview: '平定准噶尔勒铭格登山碑是新疆较少被大众游客注意到的清代碑刻遗存，属于更偏学术感和历史感的小众人文点。',
    history: '格登山碑与清代平定准噶尔战争后的纪功体系相关，是理解乾隆时期新疆统一进程、边疆治理叙事和官方纪念方式的重要实物线索。它的价值不在景观规模，而在其所承载的历史事件与政治象征意义。',
    highlights: '如果你对新疆“为何被纳入统一国家叙事”这段历史感兴趣，这类碑刻比普通打卡景点更有信息量。',
  },
  64: {
    overview: '吐峪沟石窟与麻扎村兼具石窟遗存、古村风貌与峡谷绿洲环境，是吐鲁番很有层次感的小众人文点。',
    history: '吐峪沟一带与佛教传播、古代聚落发展和后来的伊斯兰文化空间都有联系，形成了很特别的多阶段文化叠加。这里既能看到早期宗教遗存，也能感受到村落生活延续下来的历史肌理。',
    highlights: '它最大的魅力是“一个地方能看到多种文化时间层”，非常适合慢慢逛。',
  },
  65: {
    overview: '惠远古城钟鼓楼片区是伊犁清代军政城池体系的重要记忆点，适合看古城格局和边疆治理历史。',
    history: '惠远古城与清代伊犁将军驻防体系关系密切，是当时新疆西部军政管理的重要节点之一。今天虽然古城整体形态已非原貌，但钟鼓楼片区仍能帮助游客建立对清代伊犁边疆城市的直观想象。',
    highlights: '适合把伊犁从“风景伊犁”扩展到“边疆历史伊犁”的理解层面。',
  },
  66: {
    overview: '靖远寺是伊犁地区较有代表性的清代寺院空间遗存之一，建筑与场域气质都偏安静克制。',
    history: '它与清代伊犁地区多民族、多宗教并存的边疆社会结构相关，也从侧面反映了当时的军政与宗教空间关系。和惠远古城放在一起看，会更容易理解伊犁的复合历史面貌。',
    highlights: '这类点位不靠热闹取胜，而是靠“历史空间感”和安静氛围。',
  },
  67: {
    overview: '阿克苏文庙是南疆城市中较少被游客主动纳入路线的礼制建筑遗存，适合补充城市历史层次。',
    history: '文庙作为传统儒学祭祀与教化空间，反映了不同时期中原礼制文化在新疆地方城市中的落地方式。它的意义更多在城市文化史和制度传播，而非单纯建筑规模。',
    highlights: '如果你想在南疆旅行里看到更少见的“城市制度史线索”，文庙是很合适的一站。',
  },
}

const destinationTravelMetaMap = {
  1: { season: '5月-10月', stay: '半天-1天', audience: '家庭游客、首次来新疆游客、轻观光用户' },
  2: { season: '6月-10月，秋季最佳', stay: '1天-2天', audience: '摄影爱好者、自然风光游客、深度旅行用户' },
  3: { season: '5月-10月', stay: '半天-1天', audience: '自驾游客、情侣、湖景摄影用户' },
  5: { season: '6月-9月', stay: '1天', audience: '亲子、情侣、草原体验用户' },
  8: { season: '6月-10月，秋季最佳', stay: '1天-2天', audience: '慢旅行用户、摄影爱好者、住宿体验游客' },
  9: { season: '4月-10月，夜游更佳', stay: '半天-1天', audience: '人文游客、城市漫游用户、美食爱好者' },
  10: { season: '4月-10月，避开正午', stay: '2小时-半天', audience: '历史爱好者、丝路文化游客、讲解型参观用户' },
  11: { season: '4月-10月', stay: '1小时-3小时', audience: '亲子、知识型游客、吐鲁番人文线用户' },
  15: { season: '5月-10月，傍晚最佳', stay: '2小时-半天', audience: '自驾游客、地貌摄影用户、电影感风景爱好者' },
  20: { season: '6月-10月，秋季最佳', stay: '半天-1天', audience: '自然控、摄影用户、工业历史感兴趣游客' },
  22: { season: '6月-9月', stay: '1天-2天', audience: '高原公路旅行用户、重度风景爱好者、边境线路游客' },
  23: { season: '全年可去，夜间更热闹', stay: '2小时-半天', audience: '城市游客、美食用户、伴手礼采购人群' },
  24: { season: '5月-9月', stay: '2小时-半天', audience: '家庭游客、长辈、轻松休闲用户' },
  30: { season: '4月-10月，早晚更舒适', stay: '半天', audience: '西域历史爱好者、遗址参观用户、深度人文游客' },
  35: { season: '6月-9月，以通车期为准', stay: '半天-1天', audience: '自驾党、公路旅行用户、多地貌体验游客' },
  38: { season: '全年可去', stay: '2小时-半天', audience: '亲子、历史文化游客、首次来新疆用户' },
  41: { season: '5月-10月', stay: '30分钟-2小时', audience: '自驾游客、风景摄影用户、伊犁环线游客' },
  53: { season: '4月-10月', stay: '半天', audience: '深度历史爱好者、西域考古兴趣用户、南疆长线游客' },
  57: { season: '4月-10月', stay: '半天', audience: '佛教艺术爱好者、历史用户、人文深度游客' },
  59: { season: '9月-11月，秋季最佳', stay: '半天-1天', audience: '秋景摄影用户、胡杨主题旅行者、自驾游客' },
  63: { season: '4月-10月', stay: '1小时-2小时', audience: '清代边疆史爱好者、碑刻研究兴趣用户、小众人文游客' },
  64: { season: '4月-10月', stay: '2小时-半天', audience: '宗教遗存爱好者、古村漫游用户、吐鲁番深度人文游客' },
  65: { season: '4月-10月', stay: '1小时-3小时', audience: '清代伊犁史爱好者、小众古城游客、安静慢逛用户' },
  66: { season: '4月-10月', stay: '1小时-2小时', audience: '边疆宗教文化爱好者、人文深度游客、惠远线顺路游客' },
  67: { season: '4月-10月', stay: '1小时左右', audience: '南疆城市史爱好者、文庙建筑兴趣用户、小众打卡游客' },
}

const destinationVisitMetaMap = {
  1: { ticket: '旺季约 95-155 元', openHours: '通常 08:30-19:00' },
  2: { ticket: '旺季约 160-230 元', openHours: '通常 08:00-20:00' },
  3: { ticket: '旺季约 70-145 元', openHours: '通常 08:30-20:00' },
  5: { ticket: '旺季约 95-135 元', openHours: '通常 08:30-19:30' },
  8: { ticket: '旺季约 50-100 元', openHours: '通常 08:00-20:00' },
  9: { ticket: '古城主街区多为免费，部分体验单收费', openHours: '全天开放，夜游更热闹' },
  10: { ticket: '约 70-120 元', openHours: '通常 09:00-19:00' },
  11: { ticket: '约 40-80 元', openHours: '通常 09:00-19:00' },
  15: { ticket: '约 45-80 元', openHours: '通常 09:00-20:00' },
  20: { ticket: '约 90-150 元', openHours: '通常 08:30-19:30' },
  22: { ticket: '按片区或联票浮动，约 80-200 元', openHours: '通常 09:00-20:00' },
  23: { ticket: '主街区免费，演出或项目另收费', openHours: '全天开放，商铺多在 10:00 后营业' },
  24: { ticket: '约 60-100 元', openHours: '通常 08:30-19:30' },
  30: { ticket: '约 70-120 元', openHours: '通常 09:00-19:00' },
  35: { ticket: '公路通行本身免费，个别观景点单独收费', openHours: '以当年通车时间和天气管制为准' },
  38: { ticket: '多为免费或预约制，特展可能单独收费', openHours: '通常 10:00-18:30，周一闭馆情况需确认' },
  41: { ticket: '多为免费观景，停车或平台项目可能收费', openHours: '全天可看，白天能见度更好' },
  53: { ticket: '约 30-80 元，视展示区开放而定', openHours: '通常 10:00-18:00' },
  57: { ticket: '约 55-120 元', openHours: '通常 10:00-18:30，部分洞窟限流开放' },
  59: { ticket: '旺季约 50-100 元', openHours: '通常 09:00-20:00' },
  63: { ticket: '多为免费或低门票参考，建议以现场公示为准', openHours: '多为白天可看，建议 10:00-18:00 之间前往' },
  64: { ticket: '门票多为低门槛参考，联动片区以现场为准', openHours: '通常建议白天参观，约 10:00-18:00' },
  65: { ticket: '多为免费或低门票参考', openHours: '通常白天开放，约 10:00-18:00' },
  66: { ticket: '多为免费或低门票参考', openHours: '通常白天开放，寺院空间以现场公告为准' },
  67: { ticket: '多为免费或低门票参考', openHours: '通常 10:00-18:00 左右，建议提前确认' },
}

export function getDestinationById(id) {
  return destinationList.find((item) => String(item.id) === String(id))
}

export function getDestinationCulture(id) {
  const destination = getDestinationById(id)

  if (!destination) {
    return null
  }

  const customContent = destinationCultureMap[String(destination.id)] || destinationCultureMap[destination.id]
  if (customContent) {
    return customContent
  }

  return {
    overview: `${destination.name}位于${destination.location}，以${destination.category}体验为主，当前页面已收录基础景观介绍、游玩建议和路线信息。`,
    history: `${destination.name}目前在应用内以景观与玩法信息为主，更详细的历史沿革和地名由来还可以继续补充官方资料、地方志或景区展陈内容。`,
    highlights: destination.suggestion,
  }
}

export function getDestinationTravelMeta(id) {
  const destination = getDestinationById(id)

  if (!destination) {
    return null
  }

  const customMeta = destinationTravelMetaMap[String(destination.id)] || destinationTravelMetaMap[destination.id]
  if (customMeta) {
    return customMeta
  }

  const categoryDefaults = {
    '湖泊雪山': {
      season: '5月-10月',
      stay: '半天-1天',
      audience: '自然风光游客、自驾游客、摄影爱好者',
    },
    '草原森林': {
      season: '6月-9月',
      stay: '半天-1天',
      audience: '亲子、情侣、慢旅行用户',
    },
    '古城人文': {
      season: '4月-10月',
      stay: '2小时-半天',
      audience: '历史文化游客、城市漫游用户、讲解参观用户',
    },
    '沙漠峡谷': {
      season: '4月-10月，避开高温或恶劣天气',
      stay: '2小时-半天',
      audience: '地貌爱好者、自驾游客、摄影用户',
    },
    '胡杨湿地': {
      season: '9月-11月，秋季最佳',
      stay: '2小时-半天',
      audience: '秋景游客、亲子、轻休闲用户',
    },
    '峡谷地貌': {
      season: '5月-10月',
      stay: '2小时-半天',
      audience: '自驾游客、地貌摄影用户、轻徒步用户',
    },
    '城市夜游': {
      season: '全年可去，春夏秋更舒适',
      stay: '1小时-半天',
      audience: '城市漫游用户、夜游游客、美食爱好者',
    },
  }

  return categoryDefaults[destination.category] || {
    season: '全年可结合天气安排',
    stay: '2小时-半天',
    audience: '首次来访游客、轻松游用户',
  }
}

export function getDestinationVisitMeta(id) {
  const destination = getDestinationById(id)

  if (!destination) {
    return null
  }

  const customMeta = destinationVisitMetaMap[String(destination.id)] || destinationVisitMetaMap[destination.id]
  if (customMeta) {
    return customMeta
  }

  const categoryDefaults = {
    '湖泊雪山': {
      ticket: '门票多在 50-150 元区间，旺季可能浮动',
      openHours: '通常 08:30-19:30，旺季延长情况较常见',
    },
    '草原森林': {
      ticket: '门票多在 50-135 元区间，区间车可能另算',
      openHours: '通常 08:30-20:00',
    },
    '古城人文': {
      ticket: '门票多在 30-120 元区间，部分老城街区免费',
      openHours: '通常 09:00-19:00，夜游街区可更晚',
    },
    '沙漠峡谷': {
      ticket: '门票多在 40-120 元区间，项目体验可能另收费',
      openHours: '通常 09:00-20:00，受天气影响较大',
    },
    '胡杨湿地': {
      ticket: '门票多在 30-100 元区间',
      openHours: '通常 09:00-19:30，秋季旺季可能调整',
    },
    '峡谷地貌': {
      ticket: '门票多在 30-120 元区间',
      openHours: '通常 09:00-19:30',
    },
    '城市夜游': {
      ticket: '许多公共街区免费，个别演出或项目单收费',
      openHours: '全天或白天开放，夜间商户营业时间更长',
    },
  }

  return categoryDefaults[destination.category] || {
    ticket: '门票信息建议以景区当日公示为准',
    openHours: '开放时间建议以景区当日公告为准',
  }
}

export function getDouyinSearchUrl(keyword) {
  return `https://www.douyin.com/search/${encodeURIComponent(keyword)}?type=live`
}
